### ISSUE TITLE
ValidationException: Required field 'imageUrls' is missing

### ISSUE THREAD

**Issue by esanchezm** [simon-weber/gmusicapi#353]
This is the code to reproduce it:

```
from gmusicapi import Mobileclient

api = Mobileclient()
logged_in = api.login(
    'username@mail',
    'pass',
    '1234567890abcdef'
)
api.search_all_access('De caceria C.P.V.', 1)
```

And this is the error:

```
2015-07-08 12:42:46,343 - gmusicapi.Mobileclient1 (shared:281) [ERROR]: the response format for Search was not recognized.

Required field 'imageUrls' is missing

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': 'De caceria C.P.V.\n', 'max-results': 1}, 'method': 'GET'}

'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "El Club de los Poetas Violentos",\n    "artistId": "Awvhguncbebxs2slwwctqvbmj6e"\n   },\n   "score": 62.93825149536133,\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "1",\n   "track": {\n    "kind": "sj#track",\n    "title": "De caceria",\n    "artist": "c.p.v.",\n    "composer": "",\n    "album": "Lo m\xc3\xa1s Bruto de CPV",\n    "albumArtist": "C.P.V.",\n    "year": 2005,\n    "trackNumber": 5,\n    "genre": "Latin Rap/Hip-Hop en Espa\xc3\xb1ol",\n    "durationMillis": "421000",\n    "albumArtRef": [\n     {\n      "url": "http://lh5.ggpht.com/k4bX8Ywq0uEcCZqbXDrC2-Deu6Q19lVs1UZwAUHcexM6SqfBKVsRkAjKAxxyjnA514VfelpluQ"\n     }\n    ],\n    "discNumber": 1,\n    "estimatedSize": "16841698",\n    "trackType": "7",\n    "storeId": "Tkl2n7h4xd7zktzxvfqv6dqmczy",\n    "albumId": "Bc2fi7kndmi2tbiutnqhc3ybo44",\n    "artistId": [\n     "Arpwtmkfe3tvwuak5ukde4fubna"\n    ],\n    "nid": "Tkl2n7h4xd7zktzxvfqv6dqmczy",\n    "trackAvailableForSubscription": true,\n    "trackAvailableForPurchase": true,\n    "albumAvailableForPurchase": true,\n    "contentType": "2"\n   },\n   "score": 154.82424926757812,\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "6",\n   "station": {\n    "kind": "sj#radioStation",\n    "name": "El Club de los Poetas Violentos",\n    "seed": {\n     "kind": "sj#radioSeed",\n     "artistId": "Awvhguncbebxs2slwwctqvbmj6e",\n     "seedType": "3"\n    }\n   },\n   "best_result": false,\n   "navigational_result": false\n  },\n  {\n   "type": "6",\n   "station": {\n    "kind": "sj#radioStation",\n    "name": "De caceria",\n    "seed": {\n     "kind": "sj#radioSeed",\n     "trackId": "Tkl2n7h4xd7zktzxvfqv6dqmczy",\n     "seedType": "2"\n    },\n    "imageUrls": [\n     {\n      "url": "http://lh5.ggpht.com/k4bX8Ywq0uEcCZqbXDrC2-Deu6Q19lVs1UZwAUHcexM6SqfBKVsRkAjKAxxyjnA514VfelpluQ"\n     }\n    ]\n   },\n   "best_result": false,\n   "navigational_result": false\n  }\n ],\n "clusterOrder": [\n  "5",\n  "2",\n  "3",\n  "1",\n  "7",\n  "6",\n  "4",\n  "8"\n ]\n}\n'

A traceback follows:
Traceback (most recent call last):
  File "/home/esteban/src/gmusicplaylists/gmusicapi/protocol/shared.py", line 248, in perform
    cls.validate(response, parsed_response)
  File "/home/esteban/src/gmusicplaylists/gmusicapi/protocol/mobileclient.py", line 279, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/__init__.py", line 36, in validate
    return v.validate(data, schema)
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 543, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 275, in validate_items
    '{}[{}]'.format(path, index))
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 285, in validate_required
    exctype=RequiredFieldValidationError)
  File "/home/esteban/.virtualenvs/gmusicplaylists/lib/python2.7/site-packages/validictory/validator.py", line 176, in _error
    raise err
ValidationException: Required field 'imageUrls' is missing
```

**Comment by simon-weber** [comment]
Thanks! Looks like an easy fix.
