### ISSUE TITLE
ValidationException in all_access search

### ISSUE THREAD

**Issue by ar1nd4m** [simon-weber/gmusicapi#360]
Request
```
{'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'5 15', 'max-results': 50}, 'method': 'GET'}
```

Response
````
'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Bridgit Mendler",\n    "artistArtRef": "http://lh3.googleusercontent.com/4cS6OjggJVAc9QOXNV6BWWqS6aXzv0VfbXhiOKbyEb8zQFEbiLk8Msabntu2nx4-f3zHkp7O",\n    "artistId": "A4c5e3g2zgbkzekb63o3rjpcqqa",\n    "artist_bio_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "Wikipedia",\n     "source_url": "http://en.wikipedia.org/wiki/Bridgit_Mendler",\n     "license_title": "Creative Commons Attribution CC-BY-SA 4.0",\n     "license_url": "http://creativecommons.org/licenses/by-sa/4.0/legalcode"\n    }\n   },\n   "score": 101.9999771118164\n  },\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "5:15",\n    "artistArtRef": "http://lh3.googleusercontent.com/ycwd-B2OkBMLUzoBUiZJmA-xUqC4M7ZB0eAUlTGMsKmyHvXCud5OxsfWH0Za0gSqteVYDthKiQ",\n    "artistId": "Ay3eytebnwtc3jj4gkdryiydmz4"\n   },\n   "score": 78.62096405029297\n  },\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "15,5",\n    "artistArtRef": "http://lh3.googleusercontent.com/7pn3U_FMVMikjTEP_ksppBUn6Apk3qsaWQC0ha4gbsMtUsflnBtbpB8bHOAfSJG76L1n4KA0ww",\n    "artistId": "A44yfr572rhcs2wfwe375ecdacu"\n   },\n   "score": 61.912506103515625\n  },\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Vince Ballard, 5:15 & Harry Baldwin",\n    "artistArtRef": "http://lh3.googleusercontent.com/oMqUGGrnL8nt-q1rwIjvWCGny8fRU4mWxFbuXCWjZkgN5hO7KlY6fG5NtrdXZlpQImcEALbhkMw",\n    "artistId": "A6egoq5mu5hncuu5ppmq3bjl7m4"\n   },\n   "score": 16.018741607666016\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "When the Killing Ends (feat. Harry Baldwin)",\n    "albumArtist": "5:15",\n    "albumArtRef": "http://lh5.ggpht.com/oQegW4vdFoMZtTN_GMWSzHoI4lq24GPwJOeLzEk5YDpOaykawGdbzM3CJg3UN1vgPZ2Dfzpv",\n    "albumId": "Bgyfx6ohnc7dp7ugcr6rwvir2iq",\n    "artist": "5:15",\n    "artistId": [\n     "Ay3eytebnwtc3jj4gkdryiydmz4"\n    ],\n    "year": 2014\n   },\n   "score": 78.68852996826172\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Hello My Name Is...",\n    "albumArtist": "Bridgit Mendler",\n    "albumArtRef": "http://lh6.ggpht.com/2766JXK-NUT0AeuoBDPUJnpE3azJvCn4Hy2War4kSuvTEc7VOpnUAqBdCQRSvUsJTuPCH2ApLw",\n    "albumId": "B5qwdzyjluxevffnfwbioatws5u",\n    "artist": "Bridgit Mendler",\n    "artistId": [\n     "A4c5e3g2zgbkzekb63o3rjpcqqa"\n    ],\n    "description_attribution": {\n     "kind": "sj#attribution",\n     "source_title": "Laura Checkoway, Google Play"\n    },\n    "year": 2012\n   },\n   "score": 77.0848617553711\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "P\xc3\xa5 Beg\xc3\xa4ran",\n    "albumArtist": "15,5",\n    "albumArtRef": "http://lh5.ggpht.com/CH8tQwS1LU8r8AeJNWtYjfCbOSMC_ofOGoIVNPR9b1MNJdbbHrjAt6UhNKs7M7A4o9Dm9ow6Cw",\n    "albumId": "B4eqeekes7bbnlx3k5q4b5ornaq",\n    "artist": "15,5",\n    "artistId": [\n     "A44yfr572rhcs2wfwe375ecdacu"\n    ],\n    "year": 2008\n   },\n   "score": 68.79167175292969\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "15 Canciones del Recuerdo 5",\n    "albumArtist": "Cornelio Reyna",\n    "albumArtRef": "http://lh5.ggpht.com/7RNAc6xQzR3785CmY9KPTGyIHr2c2LcT-19VYgLTDSXXkMLUJad9Yth6cTvLXnXdF5O7BstWEg",\n    "albumId": "B67obehs74jtrw24swvnsh4uwca",\n    "artist": "Cornelio Reyna",\n    "artistId": [\n     "Afq5ln4oa2l5un5mtvjquf6gpay"\n    ],\n    "year": 2014\n   },\n   "score": 66.93399047851562\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "15 \xc3\x89xitos de Siempre Vol. 5",\n    "albumArtist": "Julio Jaramillo",\n    "albumArtRef": "http://lh6.ggpht.com/18YSqs2hRJV1CHOzUcKCwHh1zVCps3ZZC3AVkVgQYVANo7lGB4ocQtUqm5-1YmkHZkuNTwNZAA",\n    "albumId": "Blqzeqibgmqyvalssiczhm7ofle",\n    "artist": "Julio Jaramillo",\n    "artistId": [\n     "Abyok2k7hb7evkxztdddpegaguu"\n    ],\n    "year": 2008\n   },\n   "score": 65.54666900634766\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Road Trips Vol. 3 No. 3: 5/15/70 (Fillmore East, New York, NY)",\n    "albumArtist": "Grateful Dead",\n    "albumArtRef": "http://lh3.ggpht.com/jJ33aMlv5JHuJgv30rkK2CChEog2w8t753awZxHI5pPJ84uF6ZYAtz-htzuvHqo-4riwFyHEIA",\n    "albumId": "Bsxanldjx2gklym34hk4bb2obqy",\n    "artist": "Grateful Dead",\n    "artistId": [\n     "Aohbphpdibghz27s5wkwsbd5lhe"\n    ],\n    "year": 2010\n   },\n   "score": 64.70516967773438\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Europe \'72 Vol 15: 5/11/72 (Grote Zaal De Doelen, Rotterdam, Holland)",\n    "albumArtist": "Grateful Dead",\n    "albumArtRef": "http://lh6.ggpht.com/hYlPXEIXIu6qrDEp2b5LR1mtr9icN9Ith1_e8th1cGWVrGffgOTHDk6edWOzQYTOcTjROEfusg",\n    "albumId": "Bnlmwfrnk5iy4qlmeuozfetc2xu",\n    "artist": "Grateful Dead",\n    "artistId": [\n     "Aohbphpdibghz27s5wkwsbd5lhe"\n    ],\n    "year": 2014\n   },\n   "score": 58.309478759765625\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "15 Years Ago Volume 5",\n    "albumArtist": "Franco",\n    "albumArtRef": "http://lh6.ggpht.com/PiVjFQcp8xuaLxLq-YSLxKHn1IUQ97CtYuMKD9hreycGjD-XyNfFGn3bsyXlyis9h3PHRBraBDo",\n    "albumId": "B7zo6q4y5ooteqfohnhy7lbamke",\n    "artist": "Franco",\n    "artistId": [\n     "Ad4mjj5r2nnzefrzqxv5cxfumpq"\n    ],\n    "year": 2012\n   },\n   "score": 56.799659729003906\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "5-10-15-20 (EP)",\n    "albumArtist": "Link Wray",\n    "albumArtRef": "http://lh5.ggpht.com/Xb_tXVUECnbMMmhoVLUQAAHm-Mb5b8JpKpILA8rYhI-xI_Xy6z92mKfDTZ8my96LlD13lJ1ApHY",\n    "albumId": "Bqwez37zuivd5kom465u5dsqccm",\n    "artist": "Link Wray",\n    "artistId": [\n     "Aso2y4a3v3l2rheyc5rzhs6vbye"\n    ],\n    "year": 2004\n   },\n   "score": 53.810943603515625\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "I tuoi 15 anni, Vol. 5",\n    "albumArtist": "Natale Galletta",\n    "albumArtRef": "http://lh6.ggpht.com/86IEWGgqziplY8oaJszxSj-50zRETm_noAmSFmSdbfrJ0JSSfY5QY9r_59308Hw_nL-MG11eOw",\n    "albumId": "Bcbck4em2cejaeebyerjchwiwa4",\n    "artist": "Natale Galletta",\n    "artistId": [\n     "Azzodsymouuqbnybgdlnufanojm"\n    ],\n    "year": 2014\n   },\n   "score": 52.759071350097656\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Glenn Gould plays Beethoven: Piano Sonatas Nos. 1-3; 5-10; 12-14; 15-18; 23; 30-32",\n    "albumArtist": "Glenn Gould",\n    "albumArtRef": "http://lh3.ggpht.com/aqpyl3WnLoVsghM1FWsvUvWXp4PHAMPYxtr08PTbfir6_U6upBu65nt74O1t-egAEp2J9-LAyw",\n    "albumId": "B62h3ki4gdd52mtc2wjd32b4dnu",\n    "artist": "Glenn Gould",\n    "artistId": [\n     "Af63zso7xapjtfrg6v32lfmgy3e"\n    ],\n    "year": 2012\n   },\n   "score": 52.209716796875\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Galatians 5:15 EP",\n    "albumArtist": "The Pusher! and Leo Breanza",\n    "albumArtRef": "http://lh5.ggpht.com/FPqf9R74aCcCh9bmZ-bcOm8pSCvLDDqsbRaBzf0NWWOdeBHuLmAsgjzwfkWGfFXGDvf83FzRxA",\n    "albumId": "B2rzpet7h7tnloibfo6hpy3p6ja",\n    "artist": "The Pusher! and Leo Breanza",\n    "artistId": [\n     "Awxrw5zgw43kgbgrpfijtmyxzla",\n     "Ai3zkvc2bwrxvkynmvaskod3jum"\n    ],\n    "year": 2005\n   },\n   "score": 48.93964767456055\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Los 15 exitos mas sierre\xc3\xb1os Vol.5",\n    "albumArtist": "El Halcon De La Sierra",\n    "albumArtRef": "http://lh5.ggpht.com/1Zi5qcVnii-ADClpJLfOBQBvqTPyuDiMh1P9fehkPDKNhSHb-lyWDd0PSj6ADCJ9RGyz0Ha4",\n    "albumId": "Bhwc4xiyb2ylnwwcrwbfvvptnmm",\n    "artist": "El Halcon De La Sierra",\n    "artistId": [\n     "Aos5gngwhwlrapisymvfdxw54gq"\n    ],\n    "year": 2007\n   },\n   "score": 45.022830963134766\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "15 Exitos House Vol. 5",\n    "albumArtist": "Various Artists",\n    "albumArtRef": "http://lh5.ggpht.com/lhJTaYDyfBzwQtuHAg7KoJn_0NAfYA_IcUvZDy0bAUKxHyBWyXozeNJpRo30INRqeIHtJQD20A",\n    "albumId": "B3c7bfyo56ulx2qvqn5xbt3zsda",\n    "artist": "Various Artists",\n    "artistId": [\n     ""\n    ],\n    "year": 2000\n   },\n   "score": 41.09739685058594\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "15 Grandes Exitos Vol.5",\n    "albumArtist": "Luis & Juli\xc3\xa1n",\n    "albumArtRef": "http://lh6.ggpht.com/TV5USvSxdZ7je-4MITIEgRTp4cFNs5thqgBvNo6qbYBQntUJBpXO7M3zBtL0vErdfyHs488ecg",\n    "albumId": "Beqf66w6vutqcgtqjfdgrlfb35m",\n    "artist": "Luis & Juli\xc3\xa1n",\n    "artistId": [\n     "Ausgwkpdtthizqpomndeotxemza"\n    ],\n    "year": 2013\n   },\n   "score": 40.640377044677734\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "15 Hit Combo! Vol. 5",\n    "albumArtist": "Various Artists",\n    "albumArtRef": "http://lh3.ggpht.com/nW1pWrEbEjJn4icjohWZ-hR3TnQm3TAqBSmatG5kcjH9ulX14vrGby00EqRIVGw8hNJdK8aD8g",\n    "albumId": "Bodvnfxrkxhqauxwr5mlctqro4u",\n    "artist": "Various Artists",\n    "artistId": [\n     ""\n    ],\n    "year": 2014\n   },\n   "score": 40.640377044677734\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Hit Mix 2011 Vol. 5 (15 Chart Hits)",\n    "albumArtist": "Mix Factor",\n    "albumArtRef": "http://lh4.ggpht.com/2E44j0Q5U1R4oFwi-68V0OuAKy8cgotzGu2P_-Cuc-nIgkrYnaX4_WO3PAhbObcTfr4gVhyJxks",\n    "albumId": "Bxklnsjxrjo5opv47ht6zi6iw4i",\n    "artist": "Mix Factor",\n    "artistId": [\n     "Akmjh7klcjoqe63xj2gm47uxo2i"\n    ],\n    "year": 2011\n   },\n   "score": 40.25741958618164\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Hit Mix 2010 Vol. 5 - 15 Chart Hits",\n    "albumArtist": "Mix Factor",\n    "albumArtRef": "http://lh4.ggpht.com/gEl6NNqLg0K4cjqDjXaVzkyz2fLGh9dJ6ow9GQ95QVKY5R7J7NrwdHR64WYn7aOtCGFSV3Qs_w",\n    "albumId": "Bqozexvic2tlx4o7eep5ioboshu",\n    "artist": "Mix Factor",\n    "artistId": [\n     "Akmjh7klcjoqe63xj2gm47uxo2i"\n    ],\n    "year": 2010\n   },\n   "score": 40.25741958618164\n  },\n  {\n   "type": "3",\n   "album": {\n    "kind": "sj#album",\n    "name": "Los 15 \xc3\x89xitos. Los 5 Latino...'
```

A traceback follows:
```
Traceback (most recent call last):
  File "/Users/arindamsharma/src/gmusicapi/gmusicapi/protocol/shared.py", line 248, in perform
    cls.validate(response, parsed_response)
  File "/Users/arindamsharma/src/gmusicapi/gmusicapi/protocol/mobileclient.py", line 279, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/Library/Python/2.7/site-packages/validictory/__init__.py", line 36, in validate
    return v.validate(data, schema)
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 543, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 275, in validate_items
    '{}[{}]'.format(path, index))
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 291, in validate_blank
    self._error("cannot be blank'", value, fieldname, path=path)
  File "/Library/Python/2.7/site-packages/validictory/validator.py", line 176, in _error
    raise err
ValidationException: Value u'' for field '<obj>.entries[42].album.artist' cannot be blank'
```

**Comment by simon-weber** [comment]
Huh, odd. That restraint has been in there for a long time.

Thanks for letting me know; it's an easy enough fix.
