### ISSUE TITLE
Unicode error when reporting duplicate upload with non-ASCII filename

### ISSUE THREAD

**Issue by afluriach** [simon-weber/gmusicapi#375]
Using the Musicmanager to upload:

Normally, when you upload a file that has already been uploaded, the music manager logs a reject message like so:

```
$ upload_music_file ~/Desktop/ascii.flac 
2015-10-20 16:27:06,270 - gmusicapi.Musicmanager1 (musicmanager:510) [WARNING]: upload of '/Users/toni/Desktop/ascii.flac' rejected: TrackSampleResponse code 4: ALREADY_EXISTS(4ef2cedd-3f00-3fd9-ad98-f8b287ba3ffe)
Uploaded /Users/toni/Desktop/ascii.flac
```

However, if the filename has non-ASCII characters, the logger gives a Unicode error when trying to print the message:

```
$ upload_music_file 日本語.flac 
Uploading 日本語.flac
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)
Logged from file musicmanager.py, line 510
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)
Logged from file musicmanager.py, line 510
```

**Comment by simon-weber** [comment]
Good catch. An easy fix would be changing the first `%s` [on that line](https://github.com/simon-weber/gmusicapi/blob/b35dd3ad4414b2950996cc2ca4016bd6d7e5fcfd/gmusicapi/clients/musicmanager.py#L510) to a `%r`.

(funny that I blogged about this a year ago, haha: https://simon.codes/2014/11/24/python-logging-traps.html)

**Comment by afluriach** [comment]
OK, I have a patch. I decide to unicode() encode the filepath. I find the repr-encoded string unhelpful as it is unreadable. I think it's safe to assume if the user is processing files with Unicode names, they are using a shell with Unicode support. 

For me sys.getdefaultencoding() returns 'ascii' but it has no problem with unicode, so I don't think I'm checking the right thing. I want to add a repr-encoded fallback if the shell doesn't support Unicode.

**Comment by simon-weber** [comment]
Closed by https://github.com/simon-weber/gmusicapi/pull/433.
