### ISSUE TITLE
add GAE-specific instructions to docs

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/gmusicapi#381]
Running gmusicapi on google app engine requires a few extra steps:
* use of manual mac address 
* use of `oauth2client.client.OAuth2Credentials` for music manager
* use of requests 2.3.0
* maybe vendorizing protobufs?

It'd be nice if this was in the docs, probably around the usage/installation section.

See https://github.com/simon-weber/gmusicapi/issues/324 for more information.

**Comment by xlorepdarkhelm** [comment]
Anything using appdirs needs to be handled in the code to allow it to work in GAE (appdirs doesn't work on GAE, the filesystem is read-only), and you must set debug_logging to False.

**Comment by JVMed** [comment]
Quite keen to see a few more detailed steps on how you guys got this package to work on GAE, I cannot get past pycrypto import errors even though [GAE already has pycrypto](https://cloud.google.com/appengine/docs/python/tools/libraries27)

My GAE app so far is just the initial helloworld example with the following main.py
```python
import webapp2
import platform

from gmusicapi import Mobileclient

class MainPage(webapp2.RequestHandler):

    def get(self):
		self.response.write('Python version ' + str(platform.python_version()))


app = webapp2.WSGIApplication([
    ('/', MainPage),
], debug=True)
```

and a [folder containing all the required packages](https://cloud.google.com/appengine/docs/python/tools/libraries27) (by the way, the GAE python ver is 2.7.5). I have modified gmusicapi as described in #324:
* Commented `log_filepath = os.path.join(my_appdirs.user_log_dir, 'gmusicapi.log')` in gmusicapi/utils/utils.py
* `OAUTH_FILEPATH = oauth2client.client.OAuth2Credentials` in musicmanager.py
* also using requests 2.3.0

This is what i get if I upload pycrypto to GAE
```python
warning: could not import appdirs;  will use current directory

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/appID/someNumber/main.py", line 10, in <module>
    from gmusicapi import Mobileclient
  File "/base/data/home/apps/appID/someNumber/lib/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/base/data/home/apps/appID/someNumber/lib/gmusicapi/clients/__init__.py", line 1, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/base/data/home/apps/appID/someNumber/lib/gmusicapi/clients/webclient.py", line 9, in <module>
    import gmusicapi.session
  File "/base/data/home/apps/appID/someNumber/lib/gmusicapi/session.py", line 8, in <module>
    import gpsoauth
  File "/base/data/home/apps/appID/someNumber/lib/gpsoauth/__init__.py", line 4, in <module>
    from . import google
  File "/base/data/home/apps/appID/someNumber/lib/gpsoauth/google.py", line 4, in <module>
    from Crypto.PublicKey import RSA
  File "/base/data/home/apps/appID/someNumber/lib/Crypto/PublicKey/RSA.py", line 78, in <module>
    from Crypto import Random
  File "/base/data/home/apps/appID/someNumber/lib/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/base/data/home/apps/appID/someNumber/lib/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/base/data/home/apps/appID/someNumber/lib/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/base/data/home/apps/appID/someNumber/lib/Crypto/Random/Fortuna/FortunaGenerator.py", line 35, in <module>
    from Crypto.Util import Counter
  File "/base/data/home/apps/appID/someNumber/lib/Crypto/Util/Counter.py", line 59, in <module>
    from Crypto.Util import _counter
ImportError: cannot import name _counter
```

and if I don't

```python
warning: could not import appdirs;  will use current directory

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/appID/someNumber/main.py", line 10, in <module>
    from gmusicapi import Mobileclient
  File "/base/data/home/apps/appID/someNumber/lib/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/base/data/home/apps/appID/someNumber/lib/gmusicapi/clients/__init__.py", line 1, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/base/data/home/apps/appID/someNumber/lib/gmusicapi/clients/webclient.py", line 9, in <module>
    import gmusicapi.session
  File "/base/data/home/apps/appID/someNumber/lib/gmusicapi/session.py", line 8, in <module>
    import gpsoauth
  File "/base/data/home/apps/appID/someNumber/lib/gpsoauth/__init__.py", line 4, in <module>
    from . import google
  File "/base/data/home/apps/appID/someNumber/lib/gpsoauth/google.py", line 4, in <module>
    from Crypto.PublicKey import RSA
ImportError: No module named Crypto.PublicKey
```

**Comment by xlorepdarkhelm** [comment]
Silly question, but did you add the following to your app.yaml?

```yaml
libraries:
  - name: pycrypto
    version: "2.6"
```

**Comment by JVMed** [comment]
Cheers that fixed it, I can now begin to use the the api on GAE! Very cool. I think I might run into the same issue you raised in #382 when I get more time to play with this.
