### ISSUE TITLE
unicode/str TypeError on Musicmanager.upload

### ISSUE THREAD

**Issue by tobeorla** [simon-weber/gmusicapi#392]
What i've made:
- Follow install steps to upload music: http://unofficial-google-music-api.readthedocs.org/en/latest/usage.html#usage
- Get & set OAuth token
- python2 test.py

Python: 2.7.6
Installed lib: ffmpeg [http://johnvansickle.com/ffmpeg/]
test.py:

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    
    from gmusicapi import Musicmanager
    
    mm = Musicmanager()
    #mm.perform_oauth()
    
    mm.login()
    mm.upload('/tmp/india.mp3')

Error log:

    Traceback (most recent call last):
      File "test.py", line 10, in <module>
        mm.upload('/tmp/india.mp3')
      File "<string>", line 2, in upload
      File "/tmp/gmusicapi/gmusicapi/utils/utils.py", line 612, in wrapper
        return function(*args, **kw)
      File "<string>", line 2, in upload
      File "/tmp/gmusicapi/gmusicapi/utils/utils.py", line 589, in wrapper
        return function(*args, **kw)
      File "/tmp/gmusicapi/gmusicapi/clients/musicmanager.py", line 472, in upload
        self.uploader_id, bogus_sample)
      File "/tmp/gmusicapi/gmusicapi/clients/shared.py", line 81, in _make_call
        return protocol.perform(self.session, self.validate, *args, **kwargs)
      File "/tmp/gmusicapi/gmusicapi/protocol/shared.py", line 206, in perform
        req_kwargs = cls.build_request(*args, **kwargs)
      File "/tmp/gmusicapi/gmusicapi/protocol/shared.py", line 86, in build_request
        val = val(*args, **kwargs)
      File "<string>", line 2, in dynamic_data
      File "/tmp/gmusicapi/gmusicapi/protocol/musicmanager.py", line 64, in pb
        msg = f(*args, **kwargs)
      File "/tmp/gmusicapi/gmusicapi/protocol/musicmanager.py", line 506, in dynamic_data
        sample_msg.sample = mock_sample
      File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
        self._fields[field] = type_checker.CheckValue(new_value)
      File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/type_checkers.py", line 103, in CheckValue
        raise TypeError(message)
    TypeError: u'' has type <type 'unicode'>, but expected one of: (<type 'str'>,)

**Comment by simon-weber** [comment]
Hm, maybe newer versions of protobuf are more strict about their string types? What version of protobuf do you have installed? If you're using pip, `pip freeze` should tell you.

If it's not 2.5.0, try running `pip install protobuf==2.5.0`; that's a known-good version.

Also, as a heads up, you're likely to run into problems with https://github.com/simon-weber/gmusicapi/issues/380 even once this is fixed :disappointed:

**Comment by tobeorla** [comment]
I'm running protobuf==2.6.1
I will try downgrading, thanks for replying.

**Comment by tobeorla** [comment]
Keeps throwing the same exception:

    pip freeze | grep "protobuf"
    protobuf==2.5.0


Exception:

    /tmp/gmusicapi# python2 test.py

    Traceback (most recent call last):
      File "test.py", line 10, in <module>
        mm.upload('/tmp/india.mp3')
      File "<string>", line 2, in upload
      File "/tmp/gmusicapi/gmusicapi/utils/utils.py", line 612, in wrapper
        return function(*args, **kw)
      File "<string>", line 2, in upload
      File "/tmp/gmusicapi/gmusicapi/utils/utils.py", line 589, in wrapper
        return function(*args, **kw)
      File "/tmp/gmusicapi/gmusicapi/clients/musicmanager.py", line 472, in upload
        self.uploader_id, bogus_sample)
      File "/tmp/gmusicapi/gmusicapi/clients/shared.py", line 81, in _make_call
        return protocol.perform(self.session, self.validate, *args, **kwargs)
      File "/tmp/gmusicapi/gmusicapi/protocol/shared.py", line 206, in perform
        req_kwargs = cls.build_request(*args, **kwargs)
      File "/tmp/gmusicapi/gmusicapi/protocol/shared.py", line 86, in build_request
        val = val(*args, **kwargs)
      File "<string>", line 2, in dynamic_data
      File "/tmp/gmusicapi/gmusicapi/protocol/musicmanager.py", line 64, in pb
        msg = f(*args, **kwargs)
      File "/tmp/gmusicapi/gmusicapi/protocol/musicmanager.py", line 506, in dynamic_data
        sample_msg.sample = mock_sample
      File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 454, in setter
        type_checker.CheckValue(new_value)
      File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/type_checkers.py", line 91, in CheckValue
        raise TypeError(message)
    TypeError: u'' has type <type 'unicode'>, but expected one of: (<type 'str'>,)

**Comment by thebigmunch** [comment]
Try running with a newer version of Python 2. That is sometimes the problem for weird stuff like this.

**Comment by tobeorla** [comment]
If i try it with python3.4 test.py:

    /tmp/gmusicapi# python3.4 test.py
    Traceback (most recent call last):
      File "test.py", line 4, in <module>
        from gmusicapi import Musicmanager
      File "/tmp/gmusicapi/gmusicapi/__init__.py", line 4, in <module>
        from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
      File "/tmp/gmusicapi/gmusicapi/clients/__init__.py", line 2, in <module>
        from gmusicapi.clients.webclient import Webclient
      File "/tmp/gmusicapi/gmusicapi/clients/webclient.py", line 4, in <module>
        from urlparse import urlparse, parse_qsl
    ImportError: No module named 'urlparse'


@thebigmunch ¿which version are you using?

**Comment by thebigmunch** [comment]
I said a newer version of Python 2. gmusicapi doesn't currently support Python 3. Python 2.7.11 is the newest Python 2 release.

**Comment by jfrelinger** [comment]
I'm getting the same error, with Python 2.7.11 py-protobuf 2.6.1

**Comment by simon-weber** [comment]
I think @thebigmunch mentioned this was a side effect of some of the python 3 changes.

**Comment by thebigmunch** [comment]
Yeah. I'll put up a PR soon (tonight or tomorrow) with a bunch of little bytes/unicode issue fixes that will hopefully cure this.

**Comment by thebigmunch** [comment]
#402 should hopefully be the remedy for this. You can install it from my fork or wait for it to be merged to test it out.

**Comment by simon-weber** [comment]
I'm closing this, but feel free to reopen if #402 didn't fix this for you.
