### ISSUE TITLE
Upload auth error code 14: NOT_SUBSCRIBED

### ISSUE THREAD

**Issue by nickanallen** [simon-weber/gmusicapi#431]
Every time I try to login after doing perform_oauth(), it gives me this error:

`OSError: a valid MAC could not be determined. Provide uploader_id (and be sure to provide the same one on future runs).`

When I try to provide an uploader_id (that I randomly generated) it fails to login and throws this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/protocol/shared.py", line 248, in perform
    cls.check_success(response, parsed_response)
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/protocol/musicmanager.py", line 121, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 14: NOT_SUBSCRIBED. See http://goo.gl/O6xe7 for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/clients/musicmanager.py", line 166, in login
    self._perform_upauth(uploader_id, uploader_name))
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/clients/musicmanager.py", line 225, in _perform_upauth
    uploader_name)
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/protocol/shared.py", line 259, in perform
    e_message=e.message,
AttributeError: 'CallFailure' object has no attribute 'message'

```

Trying to do upload() anyway gives me this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-68>", line 2, in upload
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/utils/utils.py", line 619, in wrapper
    return function(*args, **kw)
  File "<decorator-gen-67>", line 2, in upload
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/utils/utils.py", line 596, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/clients/musicmanager.py", line 436, in upload
    raise NotLoggedIn("Not authenticated as an upload device;"
gmusicapi.exceptions.NotLoggedIn: Not authenticated as an upload device; run Api.login(...perform_upload_auth=True...) first.
```
Any ideas?

**Comment by thebigmunch** [comment]
Do you have Google Music enabled for your Google account?

**Comment by nickanallen** [comment]
I did, but I solved it by trying to upload a couple of songs using the desktop client then trying again. Now it works, thanks.

**Comment by thebigmunch** [comment]
Well, if you aren't running this in a virtual machine, then you'll probably want to keep track of #408.
