### ISSUE TITLE
Error when installing via pip on Ubuntu 15.10

### ISSUE THREAD

**Issue by DarkArc** [simon-weber/gmusicapi#450]
```
/usr/bin/pip run on Thu Apr  7 20:59:25 2016
Downloading/unpacking gmusicapi
  Getting page https://pypi.python.org/simple/gmusicapi/
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 670, in get_page
    resp = session.get(url, headers={"Accept": "text/html"})
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 388, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/response.py", line 49, in assert_header_parsing
    if not isinstance(headers, httplib.HTTPMessage):
AttributeError: 'module' object has no attribute 'HTTPMessage'
```

**Comment by simon-weber** [comment]
Hm. Can you try installing into a [virtualenv](https://virtualenv.pypa.io/en/latest/) instead? I have a feeling this has to do with your local environment, and a virtualenv will isolate us from it.

**Comment by thebigmunch** [comment]
So, this is from a bad interaction between older urllib3 versions and python-future's standard library aliasing. Updating requests to >= 2.8.1 and, if installed separately, urllib3 >= 1.11.1 should prevent this problem.

**Comment by simon-weber** [comment]
Feel free to reopen if this is still an issue.
