### ISSUE TITLE
Error when uploading songs with Music Manager (part 1)

### ISSUE THREAD

**Issue by azhou890** [simon-weber/gmusicapi#452]
Encountering two (possibly unrelated) errors when uploading songs to Google Music, but songs still make it onto the service. This is the first of the two:

The error happens every time after calling MusicManager.upload(). No trancoding.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 331, in getMessage
    msg = str(self.msg)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 983, in __str__
    return text_format.MessageToString(self)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 129, in MessageToString
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 172, in PrintMessage
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 205, in PrintField
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 239, in PrintFieldValue
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 167, in PrintMessage
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 205, in PrintField
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 239, in PrintFieldValue
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 172, in PrintMessage
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 205, in PrintField
    float_format=float_format)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 258, in PrintFieldValue
    out.write(text_encoding.CEscape(out_value, out_as_utf8))
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_encoding.py", line 79, in CEscape
    return ''.join(_cescape_byte_to_str[Ord(c)] for c in text)
  File "/media/sdv1/azhou890/.local/lib/python2.7/site-packages/google/protobuf/text_encoding.py", line 79, in <genexpr>
    return ''.join(_cescape_byte_to_str[Ord(c)] for c in text)
TypeError: ord() expected string of length 1, but int found
Logged from file shared.py, line 244
```

Code: 
```
import os
from gmusicapi import Musicmanager
api = Musicmanager()
api.login()

musicdir = '/media/sdv1/azhou890/directory/directory/data/sync/Music'

print('Adding files')
for subdir, dirs, files in os.walk(musicdir):
  musiclist = []
  for file in files:
    _, file_ext = os.path.splitext(file)
    if file_ext == '.mp3':
      filename = os.path.join(subdir, file)
      musiclist.append(filename)
  if musiclist:
    print('Uploading Music')
    _,_,failed = api.upload(musiclist)

    print('Checking Music')
    for failed_upload in failed:
      print(failed_upload)

api.logout()
```

Client Info:
--------------------------------------------------------
Python Version: 2.7.9

Pip Freeze:
```
Cheetah==2.4.4
Mako==1.0.0
MarkupSafe==0.23
MechanicalSoup==0.4.0
PAM==0.4.2
Pyste==0.9.10
Twisted==14.0.2
Twisted-Conch==14.0.2
Twisted-Core==14.0.2
Twisted-Lore==14.0.2
Twisted-Mail==14.0.2
Twisted-Names==14.0.2
Twisted-News==14.0.2
Twisted-Runner==14.0.2
Twisted-Web==14.0.2
Twisted-Words==14.0.2
appdirs==1.4.0
argparse==1.2.1
beautifulsoup4==4.4.1
cffi==0.8.6
characteristic==0.1.0
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
decorator==4.0.9
deluge==1.3.11
funcsigs==1.0.1
future==0.15.2
gmusicapi==9.0.0
gpsoauth==0.2.0
html5lib==0.999
httplib2==0.9.2
iotop==0.6
mock==2.0.0
mutagen==1.31
ndg-httpsclient==0.3.2
oauth2client==2.0.2
pbr==1.9.1
ply==3.4
proboscis==1.2.6.0
protobuf==3.0.0b2
pyOpenSSL==0.14
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.10
pycrypto==2.6.1
pycryptodome==3.4
pyserial==2.6
python-apt==0.9.3.12
python-dateutil==2.5.3
python-libtorrent==1.0.5
pyxdg==0.25
requests==2.4.3
rsa==3.4.2
service-identity==1.0.0
six==1.8.0
urllib3==1.9.1
validictory==1.0.1
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.1.1
```

**Comment by thebigmunch** [comment]
Do you still get the same traceback with the develop branch?

**Comment by azhou890** [comment]
Yup, same traceback.

**Comment by aug-riedinger** [comment]
Same error here ...

```
▶ python --version
Python 2.7.9

▶ pip freeze
MechanicalSoup==0.4.0
Pillow==2.6.1
Pygments==2.0.1
SOAPpy==0.12.22
appdirs==1.4.0
argparse==1.2.1
beautifulsoup4==4.4.1
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
decorator==4.0.9
defusedxml==0.4.1
dnspython==1.12.0
docutils==0.12
funcsigs==1.0.2
future==0.15.2
gmusicapi==10.0.0
gpsoauth==0.2.0
html5lib==0.999
httplib2==0.9.2
lxml==3.4.0
meld==3.12.1
mock==2.0.0
mutagen==1.32
ndg-httpsclient==0.3.2
numpy==1.8.2
oauth2client==2.1.0
pbr==1.9.1
pexpect==3.2
ply==3.4
proboscis==1.2.6.0
protobuf==3.0.0b2
pyOpenSSL==0.14
pyasn1==0.1.7
pyasn1-modules==0.0.8
pycparser==2.10
pycrypto==2.6.1
pycryptodome==3.4
pygobject==3.14.0
python-apt==0.9.3.12
python-dateutil==2.5.3
python-debian==0.1.27
python-debianbts==1.11
reportbug==6.6.3
reportlab==3.1.8
requests==2.4.3
roman==2.0.0
rsa==3.4.2
six==1.10.0
urllib3==1.9.1
validictory==1.0.1
virtualenv==1.11.6
wheel==0.24.0
wsgiref==0.1.2
wstools==0.4.3


```

**Comment by aug-riedinger** [comment]
Indeed, the songs are still uploaded.

**Comment by aug-riedinger** [comment]
No update on this? I'd really like to avoid having unnecessary error message when using the package. Makes real error detection harder.

**Comment by aug-riedinger** [comment]
I did some little digging about the issue.

It appears that the method called `ord` gets called numerous of time with strings, but once is called with a:
```
b'<25 bytes>' # text
<class 'future.types.newbytes.newbytes'> # type(text)
```

So I did some **dirty** lib editing and the single change in `/usr/local/lib/python2.7/dist-packages/google/protobuf/text_encoding.py`:

```
  Ord = ord if isinstance(text, six.string_types) else lambda x: x
  text = str(text)
  if as_utf8:
    return ''.join(_cescape_utf8_to_str[Ord(c)] for c in text)   
  return ''.join(_cescape_byte_to_str[Ord(c)] for c in text)
```

fixes the issue. 

I wanted to fix this at a higher level, but what bothers me is that at no point in the stacktrace a `gmusicapi` specific code is called. Only `/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py`.

One possibility though is that it became fixed in version `3.0.0b3` as specified [here](https://github.com/google/protobuf/blob/master/python/google/protobuf/__init__.py#L33) while gmusicapi is still using `3.0.0b2` as specified [there](https://github.com/simon-weber/gmusicapi/blob/develop/setup.py#L18).

But from my understanding, this is a `protobuf`-specific bug.

**Comment by simon-weber** [comment]
Hm. Can you try upgrading protobuf locally to see if that fixes the issue? It does seem like it's coming from protobuf - unless we're passing it something unexpected - so upgrading seems reasonable.

**Comment by aug-riedinger** [comment]
I wish but I'm not a pythonist and I have no idea how to do that.

**Comment by simon-weber** [comment]
`pip install protobuf==3.0.0b3` ought to do it (from inside your virtualenv, if you're using one).

**Comment by ferlnand** [comment]
I get the same error and don't want to do this lib editing as @aug-riedinger mentioned. 

`$ python --version
Python 2.7.11+`

> $ python --version
Python 2.7.11+

I also did the upgrade for protobuf:

`$ pip freeze | grep proto
protobuf==3.0.0b3`

**Comment by aug-riedinger** [comment]
I gave the bug another try after reinstalling my system.

For sure, the issue is python 2.7 vs 3 related.

Here's another guy that has faced the issue: https://groups.google.com/forum/#!topic/protobuf/bF-KiCHwkzk

In the source code, we can now read:

```
  # PY3 hack: make Ord work for str and bytes:
  # //platforms/networking/data uses unicode here, hence basestring.
```

as if we were executing python3 code...

@simon-weber could you explain what is the point of this lib, what it is supposed to do and how it is used?

Thanks

**Comment by simon-weber** [comment]
> what is the point of this lib

Protocol buffers itself? It's a Google serialization format; gmusicapi uses it to format data going to the Music Manager apis.

> In the source code, we can now read:

Can you link to that? I'm not sure what you're referring to.

> I wanted to fix this at a higher level, but what bothers me is that at no point in the stacktrace a gmusicapi specific code is called. Only /usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py

This seems to imply it's a bug in protobuf, rather than our compiled pb2s or client code. It looks like they released version 3.0.0 recently -- maybe that's worth a try? Or we could try and ask the protobuf folks directly.

**Comment by thebigmunch** [comment]
So I've run down the starting point of this in gmusicapi. I think this is something we could be able to work around on our end since it seems like protobuf is having an issue with a Python 3-like bytes object appearing on Python 2, namely the difference in indexing. I think we also end up butting our head against a protobuf issue I found. Protobuf has an open issue regarding bytearray support on Python 2, which has the same indexing behavior as bytes on Python 3.

So, I'll look into what the proper solution will be for gmusicapi this weekend.

**Comment by aug-riedinger** [comment]
The `# PY3 hack: make Ord work for str and bytes:` is there:
https://github.com/google/protobuf/blob/master/python/google/protobuf/text_encoding.py#L74

I considered opening an issue in [google/protobuf](https://github.com/google/protobuf), but I am absolutely incapable of reproducing the bug in another context, and I felt awkward asking for support to google for the *unofficial google play music api* ...

**Comment by thebigmunch** [comment]
This may actually propagate up to the six module, as protobuf makes use of ``six.indexbytes`` which is what is failing them on bytearrays. If there's no proper way to solve it in gmusicapi, it will likely just require waiting for it to be solved upstream.

Or, deprecate Python 2 support and schedule removal at the end of 2017 ^_^
Wishful thinking is wishful : P

**Comment by simon-weber** [comment]
@iondulgheru ran into this just now in the linked issue.

Can you try upgrading protobuf to the latest and see if that fixes it? Hopefully they've landed a fix since we last saw this.

**Comment by iondulgheru** [comment]
It seems that I have the latest version

```
[root@play gmusic]# pip install --upgrade protobuf
Requirement already up-to-date: protobuf in /usr/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg
```

```
[root@play gmusic]# pip freeze | grep proto
protobuf==3.2.0
```

**Comment by simon-weber** [comment]
Huh. @thebigmunch do you remember anything about this? I'm at a loss.

**Comment by thebigmunch** [comment]
Apparently I never linked the related protobuf issue. [This](https://github.com/google/protobuf/issues/1173) is it. As I said before, that issue is for a Python 2 bytearray which has the same behavior as Python 3 bytes and bytearray objects when getting an index, it returns an integer. This is tripping us up here due to python-future backporting a Python 3-alike bytes object that gets used.

This isn't really an issue, though, as six should really just do the better thing [here](https://bitbucket.org/gutworth/six/src/92e1c746e1abfbdb94705b821bc93766083efc54/six.py?at=default&fileviewer=file-view-default#six.py-657), which is to use a 1-length slice (``i:i+1``) which works on Python 2 bytes and bytearray objects and also on python-future's Python 3-alike bytes objects.

I never followed up because I was busy and assumed something would get done by someone on protobuf's end. But I should know better than that : P

**Comment by simon-weber** [comment]
@jimwd just saw another example of this in the linked issue.
