### ISSUE TITLE
Error when uploading songs with Music Manager (part 2)

### ISSUE THREAD

**Issue by azhou890** [simon-weber/gmusicapi#453]
Encountering two (possibly unrelated) errors when uploading songs to Google Music, but songs still make it onto the service. This is the second of the two:

The error happens after the first error (#452) when gmusicapi tries to log problems with uploading, in this instance `TrackSampleResponse code 4: ALREADY_EXISTS(...)`. It appears to be a unicode issue, because it's only happening with `Beyoncé` in the filename.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 61: ordinal not in range(128)
Logged from file musicmanager.py, line 534
```

Code: 
```
import os
from gmusicapi import Musicmanager
api = Musicmanager()
api.login()

musicdir = '/media/sdv1/azhou890/directory/directory/data/sync/Music'

print('Adding files')
for subdir, dirs, files in os.walk(musicdir):
  musiclist = []
  for file in files:
    _, file_ext = os.path.splitext(file)
    if file_ext == '.mp3':
      filename = os.path.join(subdir, file)
      musiclist.append(filename)
  if musiclist:
    print('Uploading Music')
    _,_,failed = api.upload(musiclist)

    print('Checking Music')
    for failed_upload in failed:
      print(failed_upload)

api.logout()
```

Client Info:
--------------------------------------------------------
Python Version: 2.7.9

Pip Freeze:
```
Cheetah==2.4.4
Mako==1.0.0
MarkupSafe==0.23
MechanicalSoup==0.4.0
PAM==0.4.2
Pyste==0.9.10
Twisted==14.0.2
Twisted-Conch==14.0.2
Twisted-Core==14.0.2
Twisted-Lore==14.0.2
Twisted-Mail==14.0.2
Twisted-Names==14.0.2
Twisted-News==14.0.2
Twisted-Runner==14.0.2
Twisted-Web==14.0.2
Twisted-Words==14.0.2
appdirs==1.4.0
argparse==1.2.1
beautifulsoup4==4.4.1
cffi==0.8.6
characteristic==0.1.0
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
decorator==4.0.9
deluge==1.3.11
funcsigs==1.0.1
future==0.15.2
gmusicapi==9.0.0
gpsoauth==0.2.0
html5lib==0.999
httplib2==0.9.2
iotop==0.6
mock==2.0.0
mutagen==1.31
ndg-httpsclient==0.3.2
oauth2client==2.0.2
pbr==1.9.1
ply==3.4
proboscis==1.2.6.0
protobuf==3.0.0b2
pyOpenSSL==0.14
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.10
pycrypto==2.6.1
pycryptodome==3.4
pyserial==2.6
python-apt==0.9.3.12
python-dateutil==2.5.3
python-libtorrent==1.0.5
pyxdg==0.25
requests==2.4.3
rsa==3.4.2
service-identity==1.0.0
six==1.8.0
urllib3==1.9.1
validictory==1.0.1
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.1.1
```

**Comment by thebigmunch** [comment]
Try using the develop version of gmusicapi (``pip install git+https://github.com/simon-weber/gmusicapi@develop``). I'm pretty sure this is something that's fixed in the develop branch but hasn't been released yet.

**Comment by azhou890** [comment]
Just checked, it is fixed on develop branch - thanks.

**Comment by simon-weber** [comment]
Sorry for the trouble. I'll get around to a release this weekend.
