### ISSUE TITLE
crash: 'dict' object is not callable

### ISSUE THREAD

**Issue by bong0** [simon-weber/gmusicapi#465]
The gmupload script from ... crashes in a gmusicapi routine as it seems:

```
2016-05-23 05:27:48,669 - gmusicapi.Musicmanager1 (musicmanager:460) [ERROR]: problem gathering local info of ''/home/syncer/g_music/83530180-foals-late-night.mp3''
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gmusicapi/clients/musicmanager.py", line 458, in upload
    track = musicmanager.UploadMetadata.fill_track_info(path)
  File "/usr/local/lib/python3.4/site-packages/gmusicapi/protocol/musicmanager.py", line 304, in fill_track_info
    track_set(track_f, audio[mutagen_f][0])
IndexError: list index out of range
(448/529) Failed to upload -- /home/syncer/g_music/83530180-foals-late-night.mp3 | list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/gmupload", line 9, in <module>
    load_entry_point('gmusicapi-scripts==0.3.0', 'console_scripts', 'gmupload')()
  File "/usr/local/lib/python3.4/site-packages/gmusicapi_scripts/gmupload.py", line 121, in main
    mmw.upload(songs_to_upload, enable_matching=cli['match'], delete_on_success=cli['delete-on-success'])
  File "<decorator-gen-130>", line 2, in upload
  File "/usr/local/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 619, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python3.4/site-packages/gmusicapi_wrapper/musicmanager.py", line 386, in upload
    results.append({'filepath': filepath, 'result': 'not_uploaded', 'message': not_uploaded(filepath)})
TypeError: 'dict' object is not callable
```

The track processed is https://ec-media.sndcdn.com/qQb89doDqP4v.128.mp3?f10880d39085a94a0418a7ef69b03d522cd6dfee9399eeb9a522079f66f1b83886614b57dfebd09695233d2eb15b228d235b10a0cae4aa6d181544f9f701bc7109e52eb337
(download https://soundcloud.com/foals/foals-late-night-solomun-remix via http://off.li)

**Comment by bong0** [comment]
This also seems to be a problem with other songs like https://soundcloud.com/allefarben/alle-farben-6-stunden-session1

```
Traceback (most recent call last):
  File "/usr/local/bin/gmsync", line 9, in <module>
    load_entry_point('gmusicapi-scripts==0.3.0', 'console_scripts', 'gmsync')()
  File "/usr/local/lib/python3.4/site-packages/gmusicapi_scripts/gmsync.py", line 203, in main
    mmw.upload(songs_to_upload, enable_matching=cli['match'], delete_on_success=cli['delete-on-success'])
  File "<decorator-gen-130>", line 2, in upload
  File "/usr/local/lib/python3.4/site-packages/gmusicapi/utils/utils.py", line 619, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python3.4/site-packages/gmusicapi_wrapper/musicmanager.py", line 386, in upload
    results.append({'filepath': filepath, 'result': 'not_uploaded', 'message': not_uploaded(filepath)})
TypeError: 'dict' object is not callable
```

**Comment by thebigmunch** [comment]
This isn't a gmusicapi issue, and it's fixed in the devel branch of gmusicapi-wrapper. You can install that with ``pip install --upgrade git+https://github.com/thebigmunch/gmusicapi-wrapper@devel``.

**Comment by bong0** [comment]
Ah okay, I just didn't find any issue reports on this. It seems to work now but instead having connection resets. I'll have a look at this...
