### ISSUE TITLE
Running setup.py install gives an error

### ISSUE THREAD

**Issue by TimeHorse** [simon-weber/gmusicapi#468]
I've tried on Ubuntu and Cygwin and both give the following error:

```
Installed /cygdrive/c/Users/darklord/AppData/Local/Temp/easy_install-jOj_QG/mock-2.0.0/.eggs/pbr-1.10.0-py2.7.egg
Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/cygdrive/c/Users/darklord/AppData/Local/Temp/easy_install-jOj_QG/mock-2.0.0/.eggs/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/cygdrive/c/Users/darklord/AppData/Local/Temp/easy_install-jOj_QG/mock-2.0.0/.eggs/pbr-1.10.0-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/cygdrive/c/Users/darklord/AppData/Local/Temp/easy_install-jOj_QG/mock-2.0.0/.eggs/pbr-1.10.0-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
  File "/cygdrive/c/CYGWIN64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1509, in evaluate_marker
    return cls.interpret(parser.expr(text).totuple(1)[1])
  File "/cygdrive/c/CYGWIN64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1543, in interpret
    return op(nodelist)
  File "/cygdrive/c/CYGWIN64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1457, in atom
    return cls.interpret(nodelist[2])
  File "/cygdrive/c/CYGWIN64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1543, in interpret
    return op(nodelist)
  File "/cygdrive/c/CYGWIN64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1478, in comparison
    raise SyntaxError(msg)
SyntaxError: '<' operator not allowed in environment markers
error: Setup script exited with error in setup command: Error parsing /cygdrive/c/Users/darklord/AppData/Local/Temp/easy_install-jOj_QG/mock-2.0.0/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
```

**Comment by simon-weber** [comment]
Can you trying installing into a virtualenv (and switching to pip if you're using easyinstall)? That often solves mysterious installation problems.

**Comment by TimeHorse** [comment]
```Pip install``` worked under Ububtu.  I think the project should be clear it's best installed by pip though so I'd leave this opened but change the goal to be write installation instructions into the readme.rst.

I don't know if there's a pip for cygwin but am happy with the Ubuntu install.

**Comment by simon-weber** [comment]
This is in the installation docs, but they're at least 2 clicks from the readme, haha: http://unofficial-google-music-api.readthedocs.io/en/latest/usage.html#installation. I'll add it to the readme too.

**Comment by TimeHorse** [comment]
Cheers and thanks!  Yeah, I found it but when you go to the cool web page of examples I thought there was no install but you're right, it's there and the link would pe perfect!  :)

**Comment by simon-weber** [comment]
Sure thing; thanks for bringing it up. Let me know what you think of that change.

**Comment by TimeHorse** [comment]
Looks good!  Thanks!
