### ISSUE TITLE
search() method in MobileClient doesn't work on non-paid accounts

### ISSUE THREAD

**Issue by askvictor** [simon-weber/gmusicapi#474]
After a successful login on the MobileClient, if I try to do a search using a non-subscription account, I get the following:
```
In [4]: s=api.search("neutral",100)
---------------------------------------------------------------------------
CallFailure                               Traceback (most recent call last)
<ipython-input-4-00d472560fe7> in <module>()
----> 1 s=api.search("neutral",100)

/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py in search(self, query, max_results)
   1217         """
   1218 
-> 1219         res = self._make_call(mobileclient.Search, query, max_results)
   1220 
   1221         hits = res.get('entries', [])

/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.pyc in _make_call(self, protocol, *args, **kwargs)
     82         CallFailure may be raised."""
     83 
---> 84         return protocol.perform(self.session, self.validate, *args, **kwargs)
     85 
     86     def is_authenticated(self):

/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.pyc in perform(cls, session, validate, *args, **kwargs)
    226                     err_msg += "\n(response was: %r)" % response.text
    227 
--> 228                 raise CallFailure(err_msg, call_name)
    229 
    230         try:

CallFailure: Search: 404 Client Error: Not Found for url: https://mclients.googleapis.com/sj/v2.4/query?q=neutral&max-results=100&tier=fr&hl=en_US&ct=1%2C2%2C3%2C4%2C6%2C7%2C8
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v2.4/query', u'headers': {u'Authorization': u'<omitted>'}, u'params': {u'q': 'neutral', u'max-results': 100, u'tier': u'fr', u'hl': u'en_US', u'ct': u'1,2,3,4,6,7,8'}, u'method': u'GET'})
(response was: u'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "notFound",\n    "message": "Not Found"\n   }\n  ],\n  "code": 404,\n  "message": "Not Found"\n }\n}\n')

```

It works fine on a subscription account.

**Comment by thebigmunch** [comment]
The same search works fine for me on a free account. If you haven't tried it again, do so; sometimes Google's servers just get flaky. If it still fails, the cause is something else.

**Comment by askvictor** [comment]
Funny thing is if I log in with a subscription account, it works fine, then logout and log in with a free account, it still fails. Suspect it's not a server flake problem

**Comment by thebigmunch** [comment]
@askvictor: Is this still happening for you?

**Comment by askvictor** [comment]
@thebigmunch yep; still a problem :(

**Comment by thebigmunch** [comment]
Can you give it a try with the current develop branch: ``pip install --upgrade git+https://github.com/simon-weber/gmusicapi@develop``

**Comment by askvictor** [comment]
No dice; tried develop with a couple of different accounts, and all the same issue.

**Comment by foxy82** [comment]
I'm seeing the same - I get this error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 218, in perform
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mclients.googleapis.com/sj/v2.5/query?dv=0&max-results=50&q=Happy&tier=fr&hl=en_US&ct=1%2C2%2C3%2C4%2C6%2C7%2C8%2C9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_search.py", line 12, in <module>
    search_results = api.search(query)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/mobileclient.py", line 1806, in search
    res = self._make_call(mobileclient.Search, query, max_results)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: Search: 404 Client Error: Not Found for url: https://mclients.googleapis.com/sj/v2.5/query?dv=0&max-results=50&q=Happy&tier=fr&hl=en_US&ct=1%2C2%2C3%2C4%2C6%2C7%2C8%2C9
(requests kwargs: {'params': {'dv': 0, 'max-results': 50, 'q': 'Happy', 'tier': 'fr', 'hl': 'en_US', 'ct': '1,2,3,4,6,7,8,9'}, 'method': 'GET', 'url': 'https://mclients.googleapis.com/sj/v2.5/query', 'headers': {'Authorization': '<omitted>'}})
(response was: '{"error":{"errors":[{"domain":"global","reason":"notFound","message":"Not Found"}],"code":404,"message":"Not Found"}}')`

**Comment by gowthamgts** [comment]
Am also getting the same error.

**Comment by simon-weber** [comment]
Hm, this is working fine in the build, too: https://travis-ci.org/simon-weber/gmusicapi/jobs/175548533#L514.

Can you think of something that might be different between our accounts that's keeping us from reproducing this? One thought is that it could be region-specific: do you mind sharing where your accounts were registered? So far we have coverage of US and French accounts, which both seem to work.

**Comment by foxy82** [comment]
Hey,

I'm in the UK. Free account.

**Comment by askvictor** [comment]
I'm in Australia.

**Comment by rubik** [comment]
Italy, free account. I'm getting the same error.

**Comment by grappendorf** [comment]
Germany, free account => 404.

**Comment by simon-weber** [comment]
Weird. Can someone with the 404 try reproducing it through a US vpn? It might be your actual location, rather than where the account was registered.

Either way, it sounds like we should add this to the docs, and maybe reraise the 404 as a CallFailure with more explanation.

**Comment by SewerSide666** [comment]
UK, free account, same error here.

**Comment by ndg63276** [comment]
Seems to work ok here. Free account, UK based.
