### ISSUE TITLE
(public?) mc playlist creation broken

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/gmusicapi#504]
This started breaking in builds a few days ago with a 500:

```
======================================================================
ERROR: proboscis.case.MethodTest (playlist_create)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "gmusicapi/test/server_tests.py", line 282, in playlist_create
    mc_id = self.mc.create_playlist(TEST_PLAYLIST_NAME, "", public=True)
  File "gmusicapi/clients/mobileclient.py", line 418, in create_playlist
    res = self._make_call(mutate_call, add_mutations)
  File "gmusicapi/clients/shared.py", line 82, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: BatchMutatePlaylists: 500 Server Error: Internal Server Error for url: https://mclients.googleapis.com/sj/v2.5/playlistbatch?dv=0&tier=aa&alt=json&hl=en_US
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v2.5/playlistbatch', u'headers': {u'Content-Type': u'application/json', u'Authorization': u'<omitted>'}, u'data': '{"mutations": [{"create": {"name": "gmusicapi_test_playlist", "deleted": false, "creationTimestamp": "-1", "lastModifiedTimestamp": "0", "type": "USER_GENERATED", "shareState": "PUBLIC", "description": ""}}]}', u'method': u'POST', u'params': {u'dv': 0, u'tier': u'aa', u'alt': u'json', u'hl': u'en_US'}})
(response was: u'{"error":{"errors":[{"domain":"global","reason":"backendError","message":"Backend Error"}],"code":500,"message":"Backend Error"}}')
```

Here's an example build: https://travis-ci.org/simon-weber/gmusicapi/jobs/161206576.

**Comment by thebigmunch** [comment]
I can confirm that private playlists are being created fine. It's difficult to debug this as well, since the Android app actually uses the ``playlists`` endpoint to create playlists.

**Comment by thebigmunch** [comment]
So, I just tested the Android app and got the same error response on public playlist creation occasionally. The playlist was created, but not public. Also got it when changing a private playlist to public at times. This seems like a Google server issue.

**Comment by simon-weber** [comment]
Sounds good; thanks for looking into it. I'll update this once the build starts passing again.

**Comment by JVMed** [comment]
I get the same issue when creating a public playlist; private playlists are created fine.

**Comment by simon-weber** [comment]
The build is passing again, so I think this is fixed.
