### ISSUE TITLE
All access search not working

### ISSUE THREAD

**Issue by parkerlreed** [simon-weber/gmusicapi#510]
Posted an issue over here https://github.com/mopidy/mopidy-gmusic/issues/155

Using the develop branch of both projects the search fails

````
ERROR    GMusicBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 347, in search
    result = future.get()
  File "/usr/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 296, in search
    query, uris)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 336, in _search_all_access
    values[0], max_results=50)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 31, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 117, in search_all_access
    return self.api.search_all_access(query, max_results=max_results)
AttributeError: 'Mobileclient' object has no attribute 'search_all_access'
````

**Comment by thebigmunch** [comment]
Your traceback doesn't correspond to the current code on mopidy-gmusic's develop branch. Seems like you aren't using the version you think.

**Comment by simon-weber** [comment]
Yeah, this was renamed in https://github.com/simon-weber/gmusicapi/blob/develop/HISTORY.rst#1000 from search_all_access to search. It looks like mopidy's got it in the develop branch.

**Comment by parkerlreed** [comment]
Ahh thanks seems I had something installed via pip2 that was conflicting with what I was installing via the develop branches. Installed mopidy, mopidy-gmusic, and gmusicapi from their respective repos and it works great!

**Comment by simon-weber** [comment]
No worries! Sorry for the breaking change =)

**Comment by parkerlreed** [comment]
I had actually run into this before but somehow regressed my package installs. Dejavu!
