### ISSUE TITLE
import uits_pb2 - Unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by scrimshander** [simon-weber/gmusicapi#521]
On releases 10.0.1 and 10.1.0 I am getting the following error (reverting to 10.0.0 works)

```
from gmusicapi import Mobileclient

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnmagee2/Documents/PythonEnvironments/gmusic/lib/python2.7/site-packages/gmusicapi-10.1.0-py2.7.egg/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/Users/johnmagee2/Documents/PythonEnvironments/gmusic/lib/python2.7/site-packages/gmusicapi-10.1.0-py2.7.egg/gmusicapi/clients/__init__.py", line 5, in <module>
    from gmusicapi.clients.musicmanager import Musicmanager, OAUTH_FILEPATH
  File "/Users/johnmagee2/Documents/PythonEnvironments/gmusic/lib/python2.7/site-packages/gmusicapi-10.1.0-py2.7.egg/gmusicapi/clients/musicmanager.py", line 27, in <module>
    from gmusicapi.protocol import musicmanager, upload_pb2, locker_pb2
  File "/Users/johnmagee2/Documents/PythonEnvironments/gmusic/lib/python2.7/site-packages/gmusicapi-10.1.0-py2.7.egg/gmusicapi/protocol/musicmanager.py", line 24, in <module>
    from gmusicapi.protocol import upload_pb2, locker_pb2, download_pb2
  File "/Users/johnmagee2/Documents/PythonEnvironments/gmusic/lib/python2.7/site-packages/gmusicapi-10.1.0-py2.7.egg/gmusicapi/protocol/upload_pb2.py", line 16, in <module>
    from . import locker_pb2 as locker__pb2
  File "/Users/johnmagee2/Documents/PythonEnvironments/gmusic/lib/python2.7/site-packages/gmusicapi-10.1.0-py2.7.egg/gmusicapi/protocol/locker_pb2.py", line 16, in <module>
    from . import uits_pb2 as uits__pb2
  File "/Users/johnmagee2/Documents/PythonEnvironments/gmusic/lib/python2.7/site-packages/gmusicapi-10.1.0-py2.7.egg/gmusicapi/protocol/uits_pb2.py", line 22, in <module>
    \x12\x32\n\x08url_info\x18\x08 \x01(\x0b\x32 .wireless_android_skyjam.UrlInfo\x12Z\n\x16parental_advisory_type\x18\t \x01(\x0e\x32:.wireless_android_skyjam.UitsMetadata.ParentalAdvisoryType\x12\x42\n\x10\x63opyright_status\x18\n \x01(\x0b\x32(.wireless_android_skyjam.CopyrightStatus\x12-\n\x05\x65xtra\x18\x0b \x03(\x0b\x32\x1e.wireless_android_skyjam.Extra\"A\n\x14ParentalAdvisoryType\x12\x0f\n\x0bUNSPECIFIED\x10\x01\x12\x0c\n\x08\x45XPLICIT\x10\x02\x12\n\n\x06\x45\x44ITED\x10\x03\"\xa5\x02\n\rUitsSignature\x12L\n\x0e\x61lgorithm_type\x18\x01 \x02(\x0e\x32\x34.wireless_android_skyjam.UitsSignature.AlgorithmType\x12Z\n\x15\x63\x61nonicalization_type\x18\x02 \x02(\x0e\x32;.wireless_android_skyjam.UitsSignature.CanonicalizationType\x12\x0e\n\x06key_id\x18\x03 \x02(\t\x12\r\n\x05value\x18\x04 \x02(\t\")\n\rAlgorithmType\x12\x0b\n\x07RSA2048\x10\x01\x12\x0b\n\x07\x44SA2048\x10\x02\" \n\x14\x43\x61nonicalizationType\x12\x08\n\x04NONE\x10\x01\"z\n\x04Uits\x12\x37\n\x08metadata\x18\x01 \x02(\x0b\x32%.wireless_android_skyjam.UitsMetadata\x12\x39\n\tsignature\x18\x02 \x02(\x0b\x32&.wireless_android_skyjam.UitsSignature')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by simon-weber** [comment]
This looks to be a problem in protobuf caused by incompatible versions: http://stackoverflow.com/questions/35095642/grpc-python-unexpected-keyword-argument-syntax.

Can you try uninstalling it and reinstalling a newer version?

**Comment by simon-weber** [comment]
@slothropbodine, can you post your version of python and the output of `pip freeze`?

**Comment by slothropbodine** [comment]
Pip freeze:
```
amqp==1.4.9
anyjson==0.3.3
appdirs==1.4.3
Appium-Python-Client==0.22
appnope==0.1.0
awscli==1.11.81
awsebcli==3.7.7
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.5.1
billiard==3.3.0.23
blessed==1.9.5
botocore==1.5.44
bs4==0.0.1
celery==3.1.23
cement==2.8.2
certifi==2017.4.17
cffi==1.9.1
chardet==3.0.3
click==6.7
colorama==0.3.7
coreapi==2.3.0
coreschema==0.0.4
cryptography==1.5.3
decorator==4.0.11
Django==1.8.14
django-admin-bootstrapped==2.5.7
django-rest-swagger==2.1.0
djangorestframework==3.6.2
docker==2.2.1
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
docutils==0.12
enum34==1.1.6
funcsigs==1.0.2
future==0.16.0
futures==3.1.1
gmusicapi==10.1.2
gpsoauth==0.4.1
haxor-news==0.4.1
httplib2==0.10.3
hvac==0.2.17
idna==2.5
ipaddress==1.0.17
ipython==5.4.1
ipython-genutils==0.1.0
itypes==1.1.0
Jinja2==2.8
jmespath==0.9.0
kaptan==0.5.8
Keras==1.0.6
kombu==3.0.35
libtmux==0.6.5
lxml==3.6.4
MarkupSafe==0.23
MechanicalSoup==0.7.0
mercurial==4.1
mock==2.0.0
mutagen==1.38
numpy==1.11.1
oauth2client==4.1.2
olefile==0.44
openapi-codec==1.3.1
paramiko==2.0.2
pathlib2==2.2.0
pathspec==0.3.4
pbr==1.10.0
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
proboscis==1.2.6.0
prompt-toolkit==1.0.15
protobuf==3.3.0
ptyprocess==0.5.1
py==1.4.31
pyasn1==0.1.9
pyasn1-modules==0.0.11
pycparser==2.17
pycrypto==2.6.1
pycryptodomex==3.4.6
Pygments==2.1.3
PySSTV==0.3
pytest==2.9.2
python-dateutil==2.5.3
PyTweening==1.0.3
pytz==2016.6.1
PyYAML==3.12
requests==2.17.3
rsa==3.4.2
s3transfer==0.1.10
scandir==1.4
scipy==0.17.1
selenium==2.53.6
semantic-version==2.5.0
simplegeneric==0.8.1
simplejson==3.10.0
six==1.10.0
South==1.0.2
TBB==0.1
tensorflow==0.12.1
texttable==0.8.4
Theano==0.8.2
tmuxp==1.2.8
traitlets==4.3.1
Unipath==1.1
uritemplate==3.0.0
urllib3==1.21.1
utils==0.9.0
validictory==1.1.1
wcwidth==0.1.7
websocket-client==0.37.0
```
Python Version:
```2.7.13```

**Comment by simon-weber** [comment]
Huh. That all looks fine. Do you also get 3.3.0 when you run this?

```
~$ python -c 'from google import protobuf; print protobuf.__version__'
```

**Comment by slothropbodine** [comment]
I just get this:

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by slothropbodine** [comment]
https://github.com/google/protobuf/issues/2350

Looks like potentially something to do with my tensorflow setup

**Comment by simon-weber** [comment]
Ah, yeah, it looks like you're getting a different version when importing.

I'd recommend creating a fresh virtualenv and reinstalling gmusicapi into that. That ought to isolate it from the system packages that are causing issues.

**Comment by slothropbodine** [comment]
That worked, thanks for you patience!

**Comment by simon-weber** [comment]
No problem! Glad we got it figured out.
