### ISSUE TITLE
Response format for Search was not recognized. Required field 'thumbnails' is missing.

### ISSUE THREAD

**Issue by pedracca** [simon-weber/gmusicapi#536]
Tried master first (10.1.1) and latest development (10.1.2rc1), same error.

Python version is 3.5.2 on OSX.

Request is:

```
{'headers': {'Authorization': '<omitted>'}, 'method': 'GET', 'url': 'https://mclients.googleapis.com/sj/v2.5/query', 'params': {'max-results': 50, 'ct': '1,2,3,4,6,7,8,9', 'q': 'Telephone Lady GaGa', 'hl': 'en_US', 'tier': 'aa', 'dv': 0}}
```

Response is:
```
'{"kind":"sj#searchresponse","entries":[{"type":"2","artist":{"kind":"sj#artist","name":"Lady Gaga","artistArtRef":"http://lh3.googleusercontent.com/y3oKhxvUqzXkCUv4LmFVEPQucVEYg8Kht3_qHI8M0sXyZfkpRAHeUsnRqn7c7F2od8zMk0tM7SI","artistArtRefs":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/y3oKhxvUqzXkCUv4LmFVEPQucVEYg8Kht3_qHI8M0sXyZfkpRAHeUsnRqn7c7F2od8zMk0tM7SI","aspectRatio":"2","autogen":false}],"artistId":"Ah7amohgkrydyfxgsbask752lye","artist_bio_attribution":{"kind":"sj#attribution","source_title":"Wikipedia","source_url":"https://en.wikipedia.org/wiki/Lady_Gaga","license_title":"Creative Commons Attribution CC-BY-SA 4.0","license_url":"http://creativecommons.org/licenses/by-sa/4.0/legalcode"}},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (feat. Beyoncé)","artist":"Lady Gaga","composer":"","album":"The Fame Monster","albumArtist":"Lady Gaga","year":2009,"trackNumber":6,"genre":"\'00s Pop","durationMillis":"220000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/_Fn2iVwyKoh3UmTyILewOSXcp4EmMSgSeLHKAxIN4rSUo5TkwJGMM6dHbi2oz1UnkP5ETq66Qg","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"8827325","trackType":"7","storeId":"Tr6zlzmvtxg3bnfhlgyeglwgr24","albumId":"5t7w66ic4dqvfzfg3lse6v7ncy","artistId":["h7amohgkrydyfxgsbask752lye"],"nid":"r6zlzmvtxg3bnfhlgyeglwgr24","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2","primaryVideo":{"kind":"sj#video","id":"EVBsypHzF3U"}},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (feat. Beyoncé)","artist":"Lady Gaga","composer":"Lady Gaga; Beyoncé","album":"The Fame Monster (Explicit Version)","albumArtist":"Lady Gaga","year":2009,"trackNumber":6,"genre":"Pop","durationMillis":"220000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/r28wkqZ6uZQpCKwg4ZI9ljQU2WkrQDEsoem1f2sqzHtbl69b-NFNdQkXDLF4BgOXskyNwMkNUes","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"8828370","trackType":"7","storeId":"Tgq5ewftyghbafgq26yfwbpy5dy","albumId":"nyyhyiih2uapllbha3sdtd7hoq","artistId":["h7amohgkrydyfxgsbask752lye","gfrgn4bxan5fiukdu4utb7jxyi"],"nid":"gq5ewftyghbafgq26yfwbpy5dy","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2","primaryVideo":{"kind":"sj#video","id":"EVBsypHzF3U"}},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (Kaskade Mix)","artist":"Beyoncé","composer":"Beyoncé","album":"Dancelicious","albumArtist":"Various Artists","year":2010,"trackNumber":1,"genre":"Pop","durationMillis":"324000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/mmVlaK3BF_SPOZVsWSypP1oYBquf8MNorZaidzUU1ltxHwjRkVPAWxQaV1ULlLMAjoA4KE_O","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"12978704","trackType":"7","storeId":"Tvvlajbdcbqph3dcmzcactj7acm","albumId":"m6th5llkn264lmwph2vnlqq67a","artistId":["gfrgn4bxan5fiukdu4utb7jxyi","h7amohgkrydyfxgsbask752lye"],"nid":"vvlajbdcbqph3dcmzcactj7acm","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2"},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (w/o Beyonce)","artist":"Lady Gaga","composer":"Lady Gaga","album":"This Is The Sound Of...2010","albumArtist":"Various Artists","year":2010,"trackNumber":1,"genre":"Pop","durationMillis":"221000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/zmeaSD0cdoF653b9D0T6LJ1jD4t0N4-KyBNGMYAJnQz6YIUaJ8Ws3Gmmgh6CMAMmyxkeSlxk","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"8871210","trackType":"7","storeId":"Tpzlk3cklbxp3uryv4jny3okz3q","albumId":"y2t62uthjhruz6t3n4eao4ur34","artistId":["h7amohgkrydyfxgsbask752lye"],"nid":"pzlk3cklbxp3uryv4jny3okz3q","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2","primaryVideo":{"kind":"sj#video","id":"EVBsypHzF3U"}},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone","artist":"Vitamin String Quartet","composer":"","album":"VSQ Performs Lady Gaga","albumArtist":"Vitamin String Quartet","year":2010,"trackNumber":6,"genre":"Rock","durationMillis":"189000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh5.ggpht.com/e-TDQxclladIIpfo0jt1VUpQX_RhWZ4Et_HBVzo6M7GpKVW5DO02986R4CLUCS23BsXhVybc","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"7570312","trackType":"7","storeId":"Tqnqr4kvd7qe34qjwwufx6ikkdy","albumId":"4lad2fw2suhfn2mktylqt25qme","artistId":["zh3byddgjyw42uoy47goo6u3ce"],"nid":"qnqr4kvd7qe34qjwwufx6ikkdy","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2"},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (Electrolightz Remix) (feat. Beyoncé)","artist":"Lady Gaga","composer":"","album":"Telephone (Electrolightz Remix)","albumArtist":"Lady Gaga feat. Beyoncé","year":2010,"trackNumber":1,"genre":"\'10s Pop","durationMillis":"266000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/F0x0rt2Dl0Z4gVw7TmYOf-I2RYh-Thy-JYtA1ycibOY8ySpclNo4THnAyNTtJCXsmbFGktsP","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"10653806","trackType":"7","storeId":"Ty7htz2xosbhh5vkssa5oq73yem","albumId":"kdqacwvepcgobfptcy5rzhav2i","artistId":["h7amohgkrydyfxgsbask752lye","gfrgn4bxan5fiukdu4utb7jxyi","vwvyeyevd3qgcrwtj54s5w43si"],"nid":"y7htz2xosbhh5vkssa5oq73yem","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2"},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (Passion Pit Remix) (feat. Beyoncé)","artist":"Lady Gaga","composer":"","album":"Telephone (Passion Pit Remix)","albumArtist":"Lady Gaga feat. Beyoncé","year":2010,"trackNumber":1,"genre":"\'10s Pop","durationMillis":"312000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/t53VysgYn9dgafULNlq4t_IYn9VYbg8EBnnlXK_5vsEwBBrBqJDcJQA0RxSX0q3PfR-WExIj_A","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"12512680","trackType":"7","storeId":"Tpyks6drw6nfbpad2etxi3zf3yu","albumId":"5jj5lkbcdera6qykmldx3o4vum","artistId":["h7amohgkrydyfxgsbask752lye","gfrgn4bxan5fiukdu4utb7jxyi","qfvay3isiqez6htt5dq6ezrgpm"],"nid":"pyks6drw6nfbpad2etxi3zf3yu","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2"},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (Alphabeat Remix Edit) (feat. Beyoncé)","artist":"Lady Gaga","composer":"Lady Gaga; Beyoncé","album":"The Remix (International Version)","albumArtist":"Lady Gaga","year":2010,"trackNumber":17,"genre":"Pop","durationMillis":"288000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/-O6ZS0W3A31Pc4vITjPsOkCl2a4YsHPPxO7WCcyn8s25RqJiHcR15hUIM6lZUPJnyuRkHG1g","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"11559733","trackType":"7","storeId":"Tvkr6gn4zdnv5gvbubkr4wccg2i","albumId":"k7slzxvqkkockfh5hh7xkmgxaq","artistId":["h7amohgkrydyfxgsbask752lye","dtjgob26afcctxydxvb4fygb7e","gfrgn4bxan5fiukdu4utb7jxyi"],"nid":"vkr6gn4zdnv5gvbubkr4wccg2i","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"1"},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (Crookers Vocal Remix) (feat. Beyoncé)","artist":"Lady Gaga","composer":"","album":"Telephone (Crookers Vocal Remix)","albumArtist":"Lady Gaga feat. Beyoncé","year":2010,"trackNumber":1,"genre":"\'10s Pop","durationMillis":"290000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/wnhXJU9VT76Fol-B_YWZ0FrnOL3dJ0e88M5k9aXmQUuAEfb-Tb2-RdWaaPA-wRqF8-I3do0sLg","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"11603619","trackType":"7","storeId":"T3rfbg3xnn5y7hpj452nsjd73nu","albumId":"sd373xaisc4v43elure3gn3nou","artistId":["h7amohgkrydyfxgsbask752lye","gfrgn4bxan5fiukdu4utb7jxyi","nkj463k6oa7ug22fhyav6mxdzy"],"nid":"3rfbg3xnn5y7hpj452nsjd73nu","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2"},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (Kaskade Extended Remix) (feat. Beyoncé)","artist":"Lady Gaga","composer":"","album":"Telephone (Kaskade Extended Remix)","albumArtist":"Lady Gaga feat. Beyoncé","year":2010,"trackNumber":1,"genre":"\'10s Pop","durationMillis":"324000","albumArtRef":[{"kind":"sj#imageRef","url":"http://lh3.googleusercontent.com/3Sx-8FkWqY5Su8cREiDf5lXZWxoF3pS3Qr4daCzrv87OejXySMlavDdvLqO25s68F-WtOhw3hA","aspectRatio":"1","autogen":false}],"discNumber":1,"estimatedSize":"12981839","trackType":"7","storeId":"Tuad2xo4jozjuifpogryugpojfy","albumId":"z4bg56ax3byvaxicyfynhz2lda","artistId":["h7amohgkrydyfxgsbask752lye","gfrgn4bxan5fiukdu4utb7jxyi","ksjmhl2dkqtpkkkcq7jktojqzq"],"nid":"uad2xo4jozjuifpogryugpojfy","trackAvailableForSubscription":true,"trackAvailableForPurchase":true,"albumAvailableForPurchase":true,"explicitType":"2"},"best_result":false,"navigational_result":false},{"type":"1","track":{"kind":"sj#track","title":"Telephone (Passion Pit Remix) (feat. Beyoncé)","artist":"Lady Gaga","composer":"Lady Gaga; Beyoncé","album":"The Remix (International Version)","albumArtist":"Lady Gaga","year":2010,"trackNumber":9,"genre":"Pop","durationMillis":"312000","albumArtRef":[{"kind...'
```

Traceback:
```
File "/Users/xxx/deezerexport-master/gmusicapi/protocol/mobileclient.py", line 625, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/__init__.py", line 43, in validate
    return v.validate(data, schema)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 613, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 655, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 288, in validate_properties
    path + '.' + property)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 655, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 322, in validate_items
    '{0}[{1}]'.format(path, index))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 655, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 288, in validate_properties
    path + '.' + property)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 655, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 288, in validate_properties
    path + '.' + property)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 655, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 288, in validate_properties
    path + '.' + property)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 655, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 332, in validate_required
    exctype=RequiredFieldValidationError)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/validictory/validator.py", line 201, in _error
    raise err
validictory.validator.RequiredFieldValidationError: Required field 'thumbnails' is missing
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/xxx/deezerexport-master/gmusicapi/protocol/shared.py", line 249, in perform
    cls.validate(response, parsed_response)
  File "/Users/xxx/deezerexport-master/gmusicapi/protocol/mobileclient.py", line 627, in validate
    raise_from(ValidationException(str(e)), e)
  File "<string>", line 2, in raise_from
gmusicapi.exceptions.ValidationException: Required field 'thumbnails' is missing
```

**Comment by simon-weber** [comment]
Thanks!
