### ISSUE TITLE
get_track_info(): Bad request

### ISSUE THREAD

**Issue by datamaan** [simon-weber/gmusicapi#547]
I'm trying to use the get_track_info function like shown here https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_track_info but I get a "Bad Request" response. Also happens with other track-ids.

Am I doing something wrong or has the fetchtrack api call been changed?

```
>>> mobile.get_track_info('Te2qokfjmhqxw4bnkswbfphzs4m')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-140>", line 2, in get_track_info
  File "/home/dataman/.local/lib/python2.7/site-packages/gmusicapi-10.1.3rc1-py2.7.egg/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/home/dataman/.local/lib/python2.7/site-packages/gmusicapi-10.1.3rc1-py2.7.egg/gmusicapi/clients/mobileclient.py", line 2066, in get_track_info
    return self._make_call(mobileclient.GetStoreTrack, store_track_id)
  File "/home/dataman/.local/lib/python2.7/site-packages/gmusicapi-10.1.3rc1-py2.7.egg/gmusicapi/clients/shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/dataman/.local/lib/python2.7/site-packages/gmusicapi-10.1.3rc1-py2.7.egg/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: GetStoreTrack: 400 Client Error: Bad Request for url: https://mclients.googleapis.com/sj/v2.5/fetchtrack?tier=fr&hl=en_US&dv=0&alt=json&nid=Te2qokfjmhqxw4bnkswbfphzs4m
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v2.5/fetchtrack', u'headers': {u'Content-Type': u'application/json', u'Authorization': u'<omitted>'}, u'params': {u'tier': u'fr', u'hl': u'en_US', u'dv': 0, u'alt': u'json', u'nid': 'Te2qokfjmhqxw4bnkswbfphzs4m'}, u'method': u'GET'})
(response was: u'{"error":{"errors":[{"domain":"global","reason":"badRequest","message":"Bad Request"}],"code":400,"message":"Bad Request"}}')
```

**Comment by simon-weber** [comment]
Huh. Can you try with track id `Tf3pxtcrp2tw7i6kdxzueoz7uia`? That passed in CI earlier today.

**Comment by datamaan** [comment]
That works. And now that I tried several more track ids most of them worked.
I must have gotten really unlucky before as all tracks I tried before failed.

Sorry for the false alarm and thanks for the quick answer.

**Comment by simon-weber** [comment]
No problem! Glad it's working.
