### ISSUE TITLE
Python 3.6 Compatibility

### ISSUE THREAD

**Issue by jsetton** [simon-weber/gmusicapi#575]
I recently upgraded my system to python 3.6.2 and it seems that that version may not be compatible with gmusicapi and more specifically with the pycrytodomex module due a syntax which appears to be no longer supported. I have setup a virtualenv in which I experienced the same error.

```
$ python --version
Python 3.6.2
```
```
$ pip freeze
appdirs==1.4.3
beautifulsoup4==4.6.0
certifi==2017.7.27.1
chardet==3.0.4
decorator==4.1.2
docopt-unicode==0.6.1
future==0.16.0
gmusicapi==10.1.2
gmusicapi-scripts==0.5.0
gmusicapi-wrapper==0.5.2
gpsoauth==0.4.1
httplib2==0.10.3
idna==2.6
MechanicalSoup==0.8.0
mock==2.0.0
mutagen==1.38
oauth2client==4.1.2
pbr==3.1.1
proboscis==1.2.6.0
protobuf==3.4.0
pyasn1==0.3.7
pyasn1-modules==0.1.5
pycryptodomex==3.4.7
python-dateutil==2.6.1
requests==2.18.4
rsa==3.4.2
six==1.11.0
urllib3==1.22
validictory==1.1.1
wrapt==1.10.11
```
```
$ ./gmsync
Traceback (most recent call last):
  File "./gmsync", line 7, in <module>
    from gmusicapi_scripts.gmsync import main
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gmusicapi_scripts/gmsync.py", line 63, in <module>
    from gmusicapi_wrapper import MusicManagerWrapper
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gmusicapi_wrapper/__init__.py", line 13, in <module>
    from .mobileclient import MobileClientWrapper
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gmusicapi_wrapper/mobileclient.py", line 11, in <module>
    from gmusicapi.clients import Mobileclient
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gmusicapi/clients/__init__.py", line 4, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gmusicapi/clients/webclient.py", line 20, in <module>
    import gmusicapi.session
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gmusicapi/session.py", line 11, in <module>
    import gpsoauth
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gpsoauth/__init__.py", line 4, in <module>
    from . import google
  File "/tmp/gmusicapi/lib/python3.6/site-packages/gpsoauth/google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "/tmp/gmusicapi/lib/python3.6/site-packages/Cryptodome/PublicKey/__init__.py", line 21, in <module>
    from Cryptodome.Util.asn1 import (DerSequence, DerInteger, DerBitString,
  File "/tmp/gmusicapi/lib/python3.6/site-packages/Cryptodome/Util/asn1.py", line 25, in <module>
    from Cryptodome.Util.number import long_to_bytes, bytes_to_long
  File "/tmp/gmusicapi/lib/python3.6/site-packages/Cryptodome/Util/number.py", line 387
    s = pack('>I', n & 0xffffffffL) + s
                                 ^
SyntaxError: invalid syntax
```

**Comment by simon-weber** [comment]
Huh. A brief look looks like they expect it to work with 3.6 and that you're on the latest version.

**Comment by jsetton** [comment]
That's what I saw too. Am I missing something?

**Comment by simon-weber** [comment]
Yeah, not sure what's up. I'll have to try recreating it when I get a chance.

**Comment by simon-weber** [comment]
For what it's worth, it works fine on travis: https://travis-ci.org/simon-weber/gmusicapi/builds/288287072.

**Comment by jsetton** [comment]
So it looks like the pycrytodomex setup script is not refactoring using 2to3 library in my environment for reasons I wasn't able to determine at this point. I had to do it manually which resolved my issue.

```
$ 2to3 -wWn --no-diffs /tmp/gmusicapi/lib/python3.6/site-packages/Cryptodome
```

**Comment by simon-weber** [comment]
Bizarre! Glad you got it figured out. May be worth an issue over on their repo.

**Comment by jsetton** [comment]
Ended up having the same issue when I upgraded to 3.7. After doing some additional troubleshooting, I believe I found the root cause per my comment below.

https://github.com/Legrandin/pycryptodome/issues/105#issuecomment-423775965

**Comment by simon-weber** [comment]
Woah, that's super bizarre. Yeah, I can definitely see how distributing only bytecode would cause an issue.

Thanks for following up!
