### ISSUE TITLE
'charmap' codec can't encode character '\u2764'

### ISSUE THREAD

**Issue by sevinty7** [simon-weber/gmusicapi#598]
Getting this error when I use the Mobileclient search function. Seems like google is giving back a unicode character that charmap doesn't like. Full readout of error. 

`Traceback (most recent call last):
  File "C:\Users\Derek\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 994, in emit
    stream.write(msg)
  File "C:\Users\Derek\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2764' in position 4564: character maps to <undefined>
Call stack:
  File ".\apiTests.py", line 63, in <module>
    demonstrate()
  File ".\apiTests.py", line 53, in demonstrate
    a = api.search("Listener wooden heart",max_results=1)
  File "C:\Users\Derek\AppData\Local\Programs\Python\Python36\lib\site-packages\gmusicapi\clients\mobileclient.py", line 1869, in search
    res = self._make_call(mobileclient.Search, query, max_results)
  File "C:\Users\Derek\AppData\Local\Programs\Python\Python36\lib\site-packages\gmusicapi\clients\shared.py", line 84, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "C:\Users\Derek\AppData\Local\Programs\Python\Python36\lib\site-packages\gmusicapi\protocol\shared.py", line 243, in perform
    log.debug(cls.filter_response(parsed_response))`

EDIT: search still completes, but throws error during search.

**Comment by sevinty7** [comment]
Submitted pull request on the file at issue.

**Comment by simon-weber** [comment]
Can you link the PR? I was expecting to see one against gmusicapi, but maybe it got submitted elsewhere?

**Comment by sevinty7** [comment]
@simon-weber it didn't go through the first time. It's submitted now.
