### ISSUE TITLE
ValidationException: Required field '<obj>.entries[62].track.estimatedSize' is missing

### ISSUE THREAD

**Issue by tizonia** [simon-weber/gmusicapi#601]
Hi!,

I've noticed this ValidationException (I'm running gmusicapi 11.0.0 from pip):

```
2018-02-28 18:00:12,329 - gmusicapi.Mobileclient1 (shared:281) [ERROR]: the response format for Search was not recognized.

Required field '<obj>.entries[62].track.estimatedSize' is missing

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{u'url': u'https://mclients.googleapis.com/sj/v2.5/query', u'headers': {u'Authorization': u'<omitted>'}, u'params': {u'q': 'in the gym', u'max-results': None, u'tier': u'fr', u'hl': u'en_US', u'dv': 0, u'ct': u'1,2,3,4,6,7,8,9'}, u'method': u'GET'}

u'{"kind":"sj#searchresponse","entries":[{"type":"3","album":{"kind":"sj#album","name":"In The Gym","albumArtist":"Various Artists","albumArtRef":"http://lh3.googleusercontent.com/MwO6HHNX7krkX_esdtzqatZBc97YbUwVDYHrwKQjwisGBoHWANhhEd_8-G9fwiHhl-1r4PlIzqw","albumId":"Bo36q4limtz32yyiievdfhnsyhe","artist":"Various Artists","artistId":[""],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"In The Gym - EDM","albumArtist":"Various Artists","albumArtRef":"http://lh3.googleusercontent.com/WNzmrBio8Lgd2YxrBMdGHg47xNuW6dOmSECkWxxcXa8wp4CP6TTCfXrXVusYFUpYFm5IesYQ_w","albumId":"Bxq2ssu52wl45dhklxddlszhm24","artist":"Various Artists","artistId":[""],"year":2018,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Pop in the Gym (Pop-Dance Music for Your Fitness)","albumArtist":"Various Artists","albumArtRef":"http://lh6.ggpht.com/zySVYgaCagJzPYngIYwcV3m4Cy19zVkrCPuFOoM3vPMb-LBEhujxwURZmDrVUL8MuHoW6WqnMSo","albumId":"Bg2rxy4fsqnzyg6k7w3u6rv3hd4","artist":"Various Artists","artistId":[""],"year":2015,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Reggae In The Gym","albumArtist":"Various Artists","albumArtRef":"http://lh3.googleusercontent.com/NrL7i8kwG0SOhdly6-1X0JQBSny0Uri3wXaFERX7pGpuTMFK204jF9rD3XeWcq7froIN-f1Rn9c","albumId":"Bq3ih5gfdcdif2zleldd6eayrwy","artist":"Various Artists","artistId":[""],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"In the Gym Motivation","albumArtist":"Various Artists","albumArtRef":"http://lh3.googleusercontent.com/Y7aZpdwuNbwhWOOZk9I4RlWmovwqyCImFjFbIFB4QKQ_QolT3bioekFs7iXawLGsqBEIiHH0v-s","albumId":"Bfaxtqzomik3vpami4w2n6wehkm","artist":"Various Artists","artistId":[""],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Christmas In The Gym","albumArtist":"Various Artists","albumArtRef":"http://lh3.googleusercontent.com/lwXJ0qmuDZRcQ35kjVRz4296EiVeUVgVij0AGrzQb6eK_1VTClSoL4picOvayn5xWfF6Arrl","albumId":"Bmcvhg4ylqiyxr7sxguvloq7wva","artist":"Various Artists","artistId":[""],"year":2015,"explicitType":"1"}},{"type":"3","album":{"kind":"sj#album","name":"In the Gym","albumArtist":"Private Picture","albumArtRef":"http://lh4.ggpht.com/azAUMK7Obs6r_nq0ycbRw3DIW9MODlO_PFWcO3ho4ymdzDDA7UcwWlqe7_J_bDNzoAWbtqEbuw","albumId":"Bzlqomf2v7oi7qujcwtpvwl7vpy","artist":"Private Picture","artistId":["Ascgjgrl2koxtx7n7io7wyfqybe"],"year":2011,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"R&B in the Gym","albumArtist":"R & B Chartstars","albumArtRef":"http://lh3.googleusercontent.com/cPw18exvFcc943qkfFozdS8SrO6OxeFlNyPV8wnPNQ4Dl5tcpXMPwbGXEIK3wFv2pD2MiKcn","albumId":"Bv3wuhfgwst5g3jy6bn5ucztipi","artist":"R & B Chartstars","artistId":["Ae34a2bmjcokvxpt2hf3mb46mnm","Aazueszvofymdfqejtlodgykmjq","A24c74lv2yrz5pimmbeyjvgw7gq"],"year":2015,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Sing Along in the Gym, Vol. 1","albumArtist":"Training Music, Workout Remix Factory, Running Music Workout","albumArtRef":"http://lh3.googleusercontent.com/9J82JHsa943AlNP2XlcTrnAY_yx-Mx0FLyabvRglxpYX2DifsprquB8Z6S4Op8stnOwYd5mabA","albumId":"B54m57buer6nl3p44a7rj2gduiu","artist":"Training Music, Workout Remix Factory, Running Music Workout","artistId":["Auhtfw3go6dhnp55rrakswvwqny","Agjomeghaipsjsungmr5w6dkuay","Azpo2ttlyyuibehy6qoq4cxb4ji"],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Sing Along in the Gym, Vol. 1","albumArtist":"Ultimate Workout Hits, Cardio Workout, Workout Buddy","albumArtRef":"http://lh3.googleusercontent.com/RPOdpHUNEAj19BhLt3gR-3mUI2CXoZJ5O1XGS2GNoV7xr17Mpk-e7OUwQEvJhLzLkBCvyaZ4Wg","albumId":"Brmvgaiomqcp2detqkvmfwucah4","artist":"Ultimate Workout Hits, Cardio Workout, Workout Buddy","artistId":["Aguejqwn32hsfva35iqv5rmyalq","Apre27azws3ntdnldstekaf4cjm","Agjyhmgqkkoenumeu7zk6lon22a"],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Sing Along in the Gym, Vol. 1","albumArtist":"Cardio Workout Crew, Gym Workout, The Gym All-Stars","albumArtRef":"http://lh3.googleusercontent.com/PZYskY0v2cc_dE_DqpjrmEzDbU8WwE9Ax3g2GqLA4ZDycbczyebn4qq-_iii-FzQ7TakAkGusw","albumId":"B7devdb4iiuuavhntk225m4cina","artist":"Cardio Workout Crew, Gym Workout, The Gym All-Stars","artistId":["A6exy4skd6sqqmahnihqyj2eyqe","Aw25oveupdplf6rutljnchvwlhq","A6s2fnpm3ivb7jn36mtbmlzkjda","Ay4iu3g533pqaqr4csahphhxohu"],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Sing Along in the Gym, Vol. 1","albumArtist":"Ibiza Fitness Music Workout, Spinning Workout, Workout Crew","albumArtRef":"http://lh3.googleusercontent.com/064CcbMLQXaD0Ta7TQtQZ6lrfjLYNITMrfhpsECT75VSMsvVfshp0k9hPt-pHiVkD9w3_baf","albumId":"Bygelompykhtgczl3laeqxcdzti","artist":"Ibiza Fitness Music Workout, Spinning Workout, Workout Crew","artistId":["Atb5i6mphr5x6ipswuda2vm46ie","Aw25oveupdplf6rutljnchvwlhq","Azz4vro4hjrtuwlzconpeps7uqu"],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Sing Along in the Gym, Vol. 1","albumArtist":"Gym Workout Music Series, Home Gym Class","albumArtRef":"http://lh3.googleusercontent.com/NctoSbAGxt3cIva33tKmz3U9BuoQJpWEkMCpfCCHWzyHNai9_-38atVNvW35n3Rcn9lqPjoI7og","albumId":"Bejjt2onqtkj4ut4zs2nkmrgttu","artist":"Gym Workout Music Series, Home Gym Class","artistId":["A35pw5ffgr62vv67mhiiboqzxem","Adri4zoydlzctofk3dzm4p2lgfq"],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Sing Along in the Gym, Vol. 1","albumArtist":"WORKOUT, Fitness Workout Hits, Workout Guru","albumArtRef":"http://lh3.googleusercontent.com/tBV3coJAmdRHqbGD1bTGEVhfjGOpadEfRhuU8dKUilGuIkZnUNprhpplCttKwoX6w7gIRw8nIEc","albumId":"Boii4bgh7xoodnk5aynylrou5ie","artist":"WORKOUT, Fitness Workout Hits, Workout Guru","artistId":["Aj2wmofcv6rsxhjm3kegj2akzu4","Ammxz3j6hxffm5us7zcvgg76gdq","Amdkxzbawchfxrstz6quxid6w6u"],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Sing Along in the Gym, Vol. 2","albumArtist":"Various Artists","albumArtRef":"http://lh3.googleusercontent.com/CDyDDxFn8e4PS8FijJcTg6F_83k_z3NiYtvK_AsVWkeDygTVRSkCEiI-Z0LKNPWAHKc0JsPv","albumId":"Bxhhuucphuv5swfbyzfbc6am5bq","artist":"Various Artists","artistId":[""],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Sing Along in the Gym, Vol. 1","albumArtist":"Various Artists","albumArtRef":"http://lh3.googleusercontent.com/Q4iMl5I_qedoGBQu_f4H99qTkYTCyQSQMIbdx__11wiAW4zeQvK8EsJDU6s8DxiVk47xpU-R","albumId":"Be3erj62voftf7xsash6ysce4gm","artist":"Various Artists","artistId":[""],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Winter Is Coming - Get in the Gym to Workout","albumArtist":"Various Artists","albumArtRef":"http://lh3.googleusercontent.com/T3L6nHKyvnmhxcGTR-kEsPSeaMwcBiwSn7Q4MKPS3FL2ZfDZ4gAF2S7GWV-uovLC2fpxg9yxvw","albumId":"Bpvcebsvb5e7f5oz7247rz3a2km","artist":"Various Artists","artistId":[""],"year":2017,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Happy in Shape Workout (125-142 Bpm) & DJ Mix [Ideal for Gym, Core Bodyweight, Abs, Motivation, Fitness, Cardio, Aerobics, Spin Cycle, Running & Jogging Workouts]","albumArtist":"The Allstars","albumArtRef":"http://lh3.googleusercontent.com/JaA2ZGutBRDx7iucofJgh5HPtqWWzzeHDAa-ltzlIlBggRvDAw8euOIhs2olSCtB45Scxxhg","albumId":"Bbtti3hixykflg7c43ia446xfqi","artist":"The Allstars","artistId":["Afirs3ugjjcexi63iq4noc5glfq"],"year":2016,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Happy in Shape - Bikini Ready Workout (126 - 140 Bpm) & DJ Mix [Ideal for Gym, Core Bodyweight, Abs, Motivation, Fitness, Cardio, Aerobics, Spin Cycle, Running & Jogging Workouts]","albumArtist":"The Allstars","albumArtRef":"http://lh3.googleusercontent.com/prpgux1XRJhhsbETwEwXl-f3iHn0aewkbaMThQHw_Yiun8xVJUg5LlztczB1EXaMzC2rfN-KOg","albumId":"B6hmitatlmadreshawedfuk4qza","artist":"The Allstars","artistId":["Afirs3ugjjcexi63iq4noc5glfq"],"year":2016,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Cat\u2019s In The Cradle ... Live \u201877 (Live At Huff Gym, University Of Illinois, 27/3/77)","albumArtist":"Harry Chapin","albumArtRef":"http://lh3.googleusercontent.com/pQk9HlyVEf4TMBELd0gUWB5waGiUmIqkwhrOT5iwGmUon1c_UfupjNWhDycrX2Q79nJFlbV5JQ","albumId":"B273wsvtmmrklpkf7iljwx2aciy","artist":"Harry Chapin","artistId":["Aagyx4vuum2ygp4cwu22o3yd5ua"],"year":1977,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"I\'m in the Gym","albumArtist":"Derek Hutchins","albumArtRef":"http://lh3.googleusercontent.com/okJ0UiMSBfJEaQ4_rMZEyW1uJzklI0WDkkeguvmxOH3xkHu_Ql_lu2Z-Z9rBbbC17CkC27PM","albumId":"Bbcexptkrf3rx7ooryz5rlxou5u","artist":"Derek Hutchins","artistId":["Apdckb5w662g6ugdlashpvpijnm"],"year":2013,"explicitType":"1"}},{"type":"3","album":{"kind":"sj#album","name":"Stay in the Pool","albumArtist":"Jason Didner and the Jungle Gym Jam","albumArtRef":"http://lh6.ggpht.com/AcyNRrDsmMYecMz-UL2Nls-iuUt8phRBMj6KOJtOpFKWI8X4Eielhs0YsYQnCv_xXmTTlLpP","albumId":"Bqrnyt6slrov6hwsrcu5zjy5hqq","artist":"Jason Didner and the Jungle Gym Jam","artistId":["Abnjgnhlrugs3i55idbsxhniwgm"],"year":2013,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"It\'s Raining in the Gym (Rain Maker)","albumArtist":"K.Spade the Prospect","albumArtRef":"http://lh4.ggpht.com/J3xFKL2zDW1PxGaq7SD5QYBtgTgmhmI6_NQxN2_T0lWuxN2FK6s9P1hPc0xeoft31w5lucLy","albumId":"Bytlrxodfztc3ztfebhhut76z6u","artist":"K.Spade the Prospect","artistId":["Anu7grsum5tdwfbp7mslrumqw3e"],"year":2012,"explicitType":"1"}},{"type":"3","album":{"kind":"sj#album","name":"A Spyder in the Gym on the Wall","albumArtist":"JDstreams","albumArtRef":"http://lh3.googleusercontent.com/7FgTay644SaIhREbm-EF2JdJTtp3zwUbRiF8zfZq5tQasLX2C1DRzsNUs8x2-51t27xkCkj8XeE","albumId":"Bvpzsc6n7vnyqrj3tnuzhtcbmem","artist":"JDstreams","artistId":["Apt6ajsfyggxv7dojv2f5dkeixq"],"year":2016,"explicitType":"2"}},{"type":"3","album":{"kind":"sj#album","name":"Intensive Winter Workout - Chillout Mus...'

A traceback follows:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 249, in perform
    cls.validate(response, parsed_response)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/mobileclient.py", line 642, in validate
    raise_from(ValidationException(str(e)), e)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
ValidationException: Required field '<obj>.entries[62].track.estimatedSize' is missing
```

**Comment by simon-weber** [comment]
Hm, I think this was fixed in 7428776650898cc316628ad49fa0b30579b43f3a. Was this on the develop branch?

**Comment by tizonia** [comment]
It was on the released version. Please feel free to close if already fixed.

**Comment by simon-weber** [comment]
Cool. Yup, it should be fixed. I'll cut a new release when I get a chance.
