### ISSUE TITLE
Not authenticated as an upload device

### ISSUE THREAD

**Issue by de666** [simon-weber/gmusicapi#602]
```from gmusicapi import Musicmanager
from os import path, listdir

folder = r'C:\temp\m'
cred_file = r'c:\temp\test.cred'

def main():
    mm = Musicmanager()
    mm.perform_oauth(cred_file, True)
    for song in listdir(folder):
        song_path = path.join(folder, song)
        mm.upload(song_path)
    mm.logout()

if __name__ == '__main__':
    main()
```

Executing this code, after the auth process, when it tries to upload a file I receive this error:

```Traceback (most recent call last):
  File "K:\Documents\scripts\gmusic_upload.py", line 29, in <module>
    main()
  File "K:\Documents\scripts\gmusic_upload.py", line 25, in main
    mm.upload(song_path)
  File "<decorator-gen-74>", line 2, in upload
  File "C:\Python27\lib\site-packages\gmusicapi\utils\utils.py", line 616, in wrapper
    return function(*args, **kw)
  File "<decorator-gen-73>", line 2, in upload
  File "C:\Python27\lib\site-packages\gmusicapi\utils\utils.py", line 593, in wrapper
    return function(*args, **kw)
  File "C:\Python27\lib\site-packages\gmusicapi\clients\musicmanager.py", line 460, in upload
    raise NotLoggedIn("Not authenticated as an upload device;"
NotLoggedIn: Not authenticated as an upload device; run Api.login(...perform_upload_auth=True...) first.
```
I've tried some months ago and all works well, I also have already verified the number of "my devices" inside the google music settings and there is only one device inside the list.
Can you tell me something about it?

**Comment by simon-weber** [comment]
I think there's a call to `mm.login()` missing. [The docs](http://unofficial-google-music-api.readthedocs.io/en/latest/usage.html#quickstart) have more details, but the gist of this is that you run perform_oauth once to save the credentials, then in your script only call login.
