### ISSUE TITLE
ValidationException for GetArtists

### ISSUE THREAD

**Issue by golf1052** [simon-weber/gmusicapi#652]
```
2019-07-17 16:25:55,846 - gmusicapi.Mobileclient2 (shared:285) [ERROR]: the response format for GetArtist was not recognized.

Value u'' for field '<obj>.albums[77].name' cannot be blank'

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{u'url': u'https://mclients.googleapis.com/sj/v2.5/fetchartist', u'headers': {u'Authorization': u'<omitted>'}, u'params': {u'num-related-artists': 0, u'nid': u'Avezxjvijtsidiyd26gs3xjf4pe', u'dv': 0, u'num-top-tracks': 0, u'hl': u'en_US', u'tier': u'fr', u'alt': u'json', u'include-albums': True}, u'method': u'GET'}

A traceback follows:
Traceback (most recent call last):
  File "/var/www/golf1052.com/projects/GPMNotify/GPMNotify/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 253, in perform
    cls.validate(response, parsed_response)
  File "/var/www/golf1052.com/projects/GPMNotify/GPMNotify/local/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 674, in validate
    raise_from(ValidationException(str(e)), e)
  File "/var/www/golf1052.com/projects/GPMNotify/GPMNotify/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
ValidationException: Value u'' for field '<obj>.albums[77].name' cannot be blank'
```

**Comment by simon-weber** [comment]
Wow, that's peculiar. I wonder if it's a mistake in their database.

Either way, thanks for reporting it and I'll take care of that when I have a chance.
