### ISSUE TITLE
TypeError when running Musicmanager.get_uploaded_songs()

### ISSUE THREAD

**Issue by rweichler** [simon-weber/gmusicapi#670]
python 3.8, Ubuntu 20.04. Installed using pip3.

This is what I did:
```python
import gmusicapi
mm = gmusicapi.Musicmanager()
mm.perform_oauth()
# then I did the oauth login, and then...
songs = mm.get_uploaded_songs()
```

Here's the traceback:
```python
# Traceback (most recent call last):
  # File "<stdin>", line 1, in <module>
  # File "$HOME/.local/lib/python3.8/site-packages/gmusicapi/clients/musicmanager.py", line 189, in get_uploaded_songs
    to_return = [song for chunk in to_return for song in chunk]
  # File "$HOME/.local/lib/python3.8/site-packages/gmusicapi/clients/musicmanager.py", line 189, in <listcomp>
    to_return = [song for chunk in to_return for song in chunk]
  # File "$HOME/.local/lib/python3.8/site-packages/gmusicapi/clients/musicmanager.py", line 236, in _get_all_songs
    lib_chunk = self._make_call(musicmanager.ListTracks,
  # File "$HOME/.local/lib/python3.8/site-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  # File "$HOME/.local/lib/python3.8/site-packages/gmusicapi/protocol/shared.py", line 205, in perform
    req_kwargs = cls.build_request(*args, **kwargs)
  # File "$HOME/.local/lib/python3.8/site-packages/gmusicapi/protocol/shared.py", line 84, in build_request
    val = val(*args, **kwargs)
  # File "<decorator-gen-68>", line 2, in dynamic_data
  # File "$HOME/.local/lib/python3.8/site-packages/gmusicapi/protocol/musicmanager.py", line 30, in pb
    msg = f(*args, **kwargs)
  # File "$HOME/.local/lib/python3.8/site-packages/gmusicapi/protocol/musicmanager.py", line 623, in dynamic_data
    msg.client_id = client_id
# TypeError: None has type NoneType, but expected one of: bytes, unicode
```

**Comment by rweichler** [comment]
I suppose it's worth mentioning; I'm trying to rip all my music off of Google Music before the big G shutters it later this year. If there's a another method, I'd love to know

**Comment by simon-weber** [comment]
Huh, I'm not sure what would cause that off the top of my head. I'll have to look through the code when I get a chance.

If you're just looking to download your uploaded music, though, you could try using the music manager directly to do that. I don't see it mentioned in Google's docs but I know it worked in the Windows app at one point.

**Comment by rweichler** [comment]
Perfect that's seeming to work, thanks! Hopefully it's at the highest possible encoding...

What's weird is the Linux app doesn't think it can connect to the Internet, but the Mac client works just fine so phew :D

**Comment by simon-weber** [comment]
Haha, wouldn't expect any less. Glad it's working for you.
